import {CORPORATIONS} from '../v07/institutions.js?v=0.7.6-origin-2';
const $=id=>document.getElementById(id);
const ART={attention:{title:'Home, but still at work',caption:'Jack checks another work screen while Sarah waits for him to listen. The wish to leave begins in months of missed conversations.'},city:{title:'The city that watches',caption:'San Francisco, 2041. Full shelves, closed access. A functioning city designed around corporate control.'},radio:{title:'The voice after midnight',caption:'Ben tries Bea’s smuggled receiver out of curiosity. Sarah listens from the doorway. The broadcast starts three nights of family arguments and questions, before any invitation or proof.'},departure:{title:'A van too old to snitch',caption:'Sarah checks the road. Corrected vehicle body: a side panel and door, with lights and grille at the front.'},country:{title:'Room to wonder',caption:'Let the country become larger than the family’s fear. A pause, not an advertisement for happiness.'},repair:{title:'Something that stays fixed',caption:'Jack and Ben follow a real mechanism. Useful knowledge survives without a service license.'},basin:{title:'A place you can switch off',caption:'The Ozarks refuge. Water, terrain, working infrastructure and a guarded physical boundary. No magic signal dome.'}};
$('corporations').innerHTML=CORPORATIONS.map((c,i)=>`<details><summary><span class="corp-number">${String(i+1).padStart(2,'0')}</span><span class="corp-name">${c.name}</span><span class="corp-domain">${c.domain}</span></summary><p class="corp-promise">“${c.promise}”</p><p>${c.control}</p><p><strong>On screen:</strong> ${c.clue}</p><p class="small">${c.presence}</p></details>`).join('');
$('art-gallery').innerHTML=Object.entries(ART).map(([key,a])=>`<figure><button data-view="${key}"><img src="../assets/brand-v2/${key}-1672.webp" srcset="../assets/brand-v2/${key}-836.webp 836w, ../assets/brand-v2/${key}-1672.webp 1672w" sizes="(max-width:760px) calc(100vw - 48px), 600px" width="1672" height="941" alt="${a.caption}" loading="lazy"><figcaption><span>${a.title}</span><span>Inspect ↗</span></figcaption></button><p>1672 × 941 source · lossless PNG in the kit</p></figure>`).join('');
$('type-input').addEventListener('input',e=>$('type-preview').textContent=e.target.value||'Leave the digital world behind.');
document.querySelectorAll('[data-tone]').forEach(b=>b.addEventListener('click',()=>{const light=b.dataset.tone==='light';$('logo-board').classList.toggle('light',light);document.querySelectorAll('[data-tone]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.querySelectorAll('[data-logo]').forEach(im=>im.src='../assets/signals-end/signals-end-'+im.dataset.logo+'-'+(light?'dark':'light')+'.svg');}));
let opener=null;
function fit(){document.querySelector('.viewer-stage').classList.remove('actual');$('viewer-zoom').setAttribute('aria-pressed','false');$('viewer-zoom').textContent='Actual pixels';}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{const key=b.dataset.view,a=ART[key];opener=b;fit();$('art-viewer').style.setProperty('--pixel-width',1672/(window.devicePixelRatio||1)+'px');$('viewer-title').textContent=a.title;$('viewer-meta').textContent='1672 × 941 · source-size inspection';$('viewer-image').src='../assets/brand-v2/'+key+'-1672.webp';$('viewer-image').alt=a.caption;$('viewer-file').href=$('viewer-image').src;$('viewer-caption').textContent=a.caption;$('art-viewer').showModal();document.body.style.overflow='hidden';$('viewer-close').focus();}));
$('viewer-zoom').addEventListener('click',()=>{const actual=document.querySelector('.viewer-stage').classList.toggle('actual');$('viewer-zoom').setAttribute('aria-pressed',String(actual));$('viewer-zoom').textContent=actual?'Fit artwork':'Actual pixels';});
$('viewer-close').addEventListener('click',()=>$('art-viewer').close());$('art-viewer').addEventListener('close',()=>{document.body.style.overflow='';opener?.focus({preventScroll:true});});$('art-viewer').addEventListener('click',e=>{if(e.target===$('art-viewer')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
const luminance=hex=>{const rgb=hex.match(/[a-f\d]{2}/gi).map(h=>parseInt(h,16)/255).map(c=>c<=.04045?c/12.92:((c+.055)/1.055)**2.4);return .2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2];};
for(const [id,a,b] of [['contrast-paper','F1EADB','17282B'],['contrast-sage','17282B','9CAA77']]){const x=luminance(a),y=luminance(b);$(id).textContent=((Math.max(x,y)+.05)/(Math.min(x,y)+.05)).toFixed(1)+':1';}
