import {DIRECTIONS} from './directions.js?v=signals-end-02';
const $=id=>document.getElementById(id),asset=c=>'../assets/signals-end-02/'+c.id+'.webp';
$('choices').innerHTML=DIRECTIONS.map((c,i)=>`<button data-direction="${c.id}" aria-pressed="false"><span>0${i+1} / ${c.type}</span><strong>${c.name}</strong></button>`).join('');
$('all-directions').innerHTML=DIRECTIONS.map((c,i)=>`<figure class="card"><button data-direction="${c.id}" data-scroll aria-label="Inspect direction ${i+1}, ${c.name}"><img src="${asset(c)}" width="1536" height="1024" loading="lazy" alt="Signals End ${c.name} concept: custom wordmark, abstract mark and type specimen"><figcaption><strong>0${i+1} / ${c.name}</strong><small>${c.type} · ${c.summary}</small></figcaption></button></figure>`).join('');
function show(id,scroll=false){const c=DIRECTIONS.find(c=>c.id===id)||DIRECTIONS.find(c=>c.selected)||DIRECTIONS[0];$('direction-type').textContent=c.type;$('direction-name').textContent=c.name;$('application-title').textContent=c.name;$('direction-summary').textContent=c.summary;$('direction-detail').textContent=c.detail;$('recommendation').textContent=c.selected?'SELECTED IDENTITY':'';const src=asset(c);$('concept-sheet').src=src;$('concept-sheet').alt='Signals End — '+c.name+' custom lettering, abstract mark and type specimen';$('full-size').href=src;$('applied-mark').src=src;$('applied-mark').style.clipPath='inset(0 0 '+(100-c.titleCropHeight/1024*100)+'% 0)';$('applied-mark').parentElement.style.aspectRatio='1536 / '+c.titleCropHeight;$('application-note').textContent='CONCEPT APPLICATION / '+c.name.toUpperCase();$('download').href=src;$('download').download='Signals-End-'+c.id+'.webp';$('swatches').innerHTML=c.colors.map(color=>`<span><i style="background:${color}"></i>${color.toUpperCase()}</span>`).join('');document.querySelectorAll('#choices button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.direction===c.id)));history.replaceState(null,'','#'+c.id);if(scroll)$('key-art').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth',block:'start'});}
document.addEventListener('click',e=>{const b=e.target.closest('[data-direction]');if(b)show(b.dataset.direction,b.hasAttribute('data-scroll'));});window.addEventListener('hashchange',()=>show(location.hash.slice(1)));show(location.hash.slice(1));

document.addEventListener('click',e=>{const b=e.target.closest('[data-scene]');if(!b)return;document.getElementById('key-art').style.backgroundImage="linear-gradient(90deg,#0815179c,transparent 80%),url('../assets/candid-04/"+b.dataset.scene+".webp')";document.querySelectorAll('[data-scene]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));});
$('full-size').addEventListener('click',e=>{e.preventDefault();$('zoom-sheet').src=$('concept-sheet').src;$('zoom-sheet').alt=$('concept-sheet').alt;$('zoom-title').textContent=$('direction-name').textContent+' / lettering detail';$('zoom').showModal();});$('close-zoom').addEventListener('click',()=>$('zoom').close());
