import {spend,log,clamp,finish} from './state.js?v=0.6.0-family-02';
export function threatLabel(s){return s.threat.heat>1?'PURSUED':s.threat.identified?'PLATE RECORDED':'UNSEEN';}
export function collectorOptions(s){const radio=s.packed.includes('radio');const options=[
 {id:'detour',label:radio?'Take Frank’s service lane':'Take the county lane',detail:`${radio?'1 hour · 2 fuel':'2 hours · 4 fuel'} · 4% van · stay off the scanner`,disabled:s.fuel<(radio?2:4)},
 !s.threat.permitUsed?{id:'papers',label:'Use the county permit',detail:'45 minutes · exemption used · your plate is recorded'}:{id:'escape',label:'Break through the rear lane',detail:'2 fuel · 12% van · they will pursue',disabled:s.fuel<2},
 ...(s.threat.permitUsed?Object.keys(s.parts).filter(k=>s.parts[k].length).slice(0,1).map(part=>({id:'trade:'+part,label:'Surrender the '+part,detail:'Lose one spare · 2 hours · leave under watch'})):[])
 ];if(options.every(o=>o.disabled))options.push({id:'surrender',label:'Keep the family safe',detail:'Leave the van · relief transport · end this attempt'});return options;}
export function resolveCollector(s,id){const available=collectorOptions(s).find(o=>o.id===id);if(!available||available.disabled)throw Error('That way out is unavailable.');
 if(id==='surrender'){finish(s,'stranded','The family stays together.','With no way around the roadblock, you surrender the van and return under escort.');return;}
 if(id==='detour'){const radio=s.packed.includes('radio');s.fuel-=radio?2:4;s.condition=clamp(s.condition-4);spend(s,radio?1:2);s.threat.heat=Math.max(0,s.threat.heat-1);log(s,'Off the camera grid',radio?'Frank’s radio warning put you on the service lane before the scanner.':'The county lane cost fuel and a hard scrape. They did not get a new scan.');}
 else if(id==='papers'){s.threat.permitUsed=true;s.threat.identified=true;s.threat.heat=1;spend(s,.75);log(s,'One exemption. Used.','The officer stamps VOID across the permit. “Next time, you return with us.” Your plate is in the registry.');}
 else if(id==='escape'){s.fuel-=2;s.condition=clamp(s.condition-12);s.threat.identified=true;s.threat.heat=2;spend(s,.5);log(s,'The barrier gives way','Sarah takes the rear lane. The van loses paint and fuel. A recovery truck is following the route.');}
 else {const part=id.split(':')[1];s.parts[part].shift();s.threat.identified=true;s.threat.heat=1;spend(s,2);log(s,'Property retained',`They take your spare ${part} as collateral. You leave, watched. That part cannot repair the van now.`);}
 s.threat.firstEncounter=true;s.threat.relief=32;s.threat.encounters++;s.stats.encounters++;s.flags.lastConflict='collectors';
}
export function makeIncident(s,r){
 if(!s.threat.firstEncounter||(r.monitored&&(s.threat.relief<=0||r.id==='r6')&&(s.threat.heat>0||r.id==='r5'))){return {id:'collectors',collectors:true,title:s.threat.permitUsed?'Your exemption is gone':'White lights. Amber bars.',body:s.threat.identified?'A camera flags the van. The same gray truck blocks the exit. The county lane is still open.':'A workforce recovery squad is scanning the main lane. An unrelated camper is being towed back toward the city.',image:s.threat.permitUsed?'blocked':'squad'};}
 if(r.kind==='storm')return {id:'flood',title:'The water is rising',body:'The low crossing is washing out. The high bridge is clear, but the turnoff burns fuel.',image:'storm',options:[{id:'careful',label:'Use the high bridge',detail:'1 hour · 3 fuel · keep the cargo dry',fuel:3,hours:1},{id:'push',label:'Cross the flooded road',detail:`10% van · ${s.cargo?(s.flags.tarp?12:30)+'% filters':'wet equipment'}`,damage:10,cargo:s.flags.tarp?12:30}]};
 if(r.kind==='rough')return {id:'washout',title:'A wheel over the edge',body:'The shoulder falls into the creek. The van is too loaded to trust the narrow strip of asphalt.',image:'plaza',options:[{id:'careful',label:'Unload and guide it across',detail:'1.5 hours · 7% rest · protects the van',hours:1.5,energy:7},{id:'push',label:'Keep the wheels turning',detail:'14% van · 12% filters if aboard',damage:14,cargo:12}]};
 if(!s.fan)return {id:'cooling',title:'The engine is losing coolant',body:'The seized fan has cooked another hose joint. Coasting will keep it alive, but this cannot go on forever.',image:'repair-family',options:[{id:'careful',label:'Cool it and refill',detail:'3 hours · 2 fuel · 3% van',hours:3,fuel:2,damage:3},{id:'push',label:'Run it hot',detail:'22% van · 1 fuel · faster arrival',damage:22,fuel:1}]};
 return {id:'neighbor',title:'A family at the closed pumps',body:'A father holds up an empty can. His radio still works. He knows which roads the Collectors are using.',image:'market',options:[{id:'careful',label:'Share 3 fuel',detail:'3 fuel · 30 minutes · a safe contact at the ridge',fuel:3,hours:.5,intel:true},{id:'push',label:'Keep the reserve',detail:'No cost · leave the family at the pumps'}]};
}
export function incidentOptions(s){return s.incident.collectors?collectorOptions(s):s.incident.options.map(o=>({...o,disabled:s.fuel<(o.fuel||0)}));}
export function resolveIncident(s,id){if(s.incident.collectors){resolveCollector(s,id);return;}const o=incidentOptions(s).find(x=>x.id===id);if(!o||o.disabled)throw Error('You cannot afford that choice.');s.fuel-=o.fuel||0;s.condition=clamp(s.condition-(o.damage||0));s.energy=clamp(s.energy-(o.energy||0));if(s.cargo)s.cargo.condition=clamp(s.cargo.condition-(o.cargo||0));if(o.intel)s.flags.safeContact=true;spend(s,o.hours||0);log(s,s.incident.title,`${o.label}. ${o.intel?'The family gives you a ridge contact and a quiet approach.':'The choice follows you down the road.'}`);s.flags.lastConflict=s.incident.id;}
