import {PARTS,random} from './world.js?v=0.6.0-candid-04';
import {clamp,log,hurt,slots} from './state.js?v=0.6.0-candid-04';
import {resolveCollector} from './conflict.js?v=0.6.0-candid-04';
export const YARD={cover:{x:.71,y:.34,w:.28,h:.39},rear:{x:.8,y:.255},front:{x:.12,y:.83},hide:{x:.76,y:.29}};
export const layoutFor=()=>YARD;
export const SITE_NAMES={yard:'Bea’s service yard',river:'The shuttered fuel stop',pump:'Flooded maintenance shed',freight:'Roadside freight depot',ridge:'The abandoned county workshop'};
export function itemsFor(s){const yard=s.node==='yard';return [
 {id:'a',type:yard?'fan':'relay',name:yard?'Cooling fan':'Pump relay',object:yard?'Irrigation engine':'Control cabinet',x:.255,y:.397,quality:88,hazard:'bracket'},
 {id:'d',type:'fuel',name:'8 fuel',object:'Reserve fuel',x:.468,y:.384,quality:100,hazard:null},
 {id:'b',type:'tire',name:'Spare tire',object:'Tire rack',x:.44,y:.375,quality:78,hazard:'shelf'},
 {id:'c',type:'food',name:'2 sealed meals',object:'Break-room locker',x:.527,y:.328,quality:100,hazard:'alarm'}
 ].map(i=>({...i,progress:0,taken:false,safe:!i.hazard,inspected:false}));}
export function startSalvage(s){if(s.siteMemory[s.node]?.sealed)throw Error('The Collectors sealed this site. Try a trader or the next stop.');s.sites[s.node]??=itemsFor(s);if(s.sites[s.node].every(i=>i.taken))throw Error('This site is picked over.');const memory=s.siteMemory[s.node]||{};s.activity={type:'salvage',elapsed:memory.elapsed||0,phase:'explore',selected:s.sites[s.node].find(i=>!i.taken).id,working:null,collected:[],player:{x:.28,y:.56,hiding:false,target:null},patrol:structuredClone(memory.patrol||{state:'absent',elapsed:0,seen:0}),notice:'Take what you need. Quiet work takes 11 seconds. Forcing a live machine can injure your hand.'};s.mode='salvage';}
export function saveSite(s){const g=s.activity;if(g?.type==='salvage')s.siteMemory[s.node]={...s.siteMemory[s.node],elapsed:g.elapsed,patrol:structuredClone(g.patrol)};}
export function schedulePatrol(s){const g=s.activity;if(g.patrol.state!=='absent')return;g.patrol={state:'warning',elapsed:0,seen:0};s.threat.firstEncounter=true;s.threat.encounters++;s.stats.encounters++;g.notice='Amber lights. Twelve seconds until they reach the gate. Grab one more thing, hide, or leave.';if(!s.reel.gallery.includes('collectors'))s.reel.gallery.push('collectors');}
function extract(s,item,method){const g=s.activity;if(PARTS[item.type]&&slots(s)>=7){g.working=null;g.phase='explore';g.notice='Locker full. Leave room before taking another part.';return;}let quality=item.quality;if(method==='force'&&item.hazard){quality-=20;s.health=clamp(s.health-9);s.effects.handUntil=s.hour+8;s.flags.handInjury=true;log(s,'A torn glove. A hurt hand.','The live bracket caught Jack’s palm. Repairs take longer for the next eight hours. Sarah wraps it before he continues.');g.notice='Jack’s hand is hurt. Repairs will take longer. The alarm brings them closer.';schedulePatrol(s);g.patrol.elapsed+=5;}else g.notice=item.name+' aboard. Leave now, or risk one more?';if(PARTS[item.type])s.parts[item.type].push(quality);else if(item.type==='fuel')s.fuel=Math.min(50,s.fuel+8);else s.meals+=2;item.taken=true;item.progress=1;g.collected.push(item.name);s.stats.salvaged++;g.working=null;g.phase='explore';if(s.node==='yard'&&item.type==='fan'){s.flags.recoveredFan=true;schedulePatrol(s);}}
export function salvageAction(s,a){if(!['inspect','extract','hide','exitSite','cancelWork','collectorChoice'].includes(a.type))return false;if(s.mode!=='salvage')throw Error('Enter a site first.');const g=s.activity;
 if(a.type==='collectorChoice'){if(g.phase!=='intercept')throw Error('No officer is stopping you.');const count=s.stats.encounters;resolveCollector(s,a.id);s.stats.encounters=count;s.threat.encounters=Math.max(1,s.threat.encounters-1);if(s.mode==='ending')return true;g.phase='exit';g.patrol.state='gone';s.siteMemory[s.node]={sealed:true};saveSite(s);return true;}
 if(g.phase==='intercept')throw Error('Deal with the officer first.');
 if(a.type==='inspect'){if(g.working)throw Error('Put the tools down first.');const item=s.sites[s.node].find(i=>i.id===a.id&&!i.taken);if(!item)throw Error('That object is picked over.');g.selected=a.id;g.player.hiding=false;g.notice=item.name+'. '+(item.hazard?'Free the '+item.hazard+' quietly, or force it and risk a hurt hand.':'The sealed reserve can be recovered safely.');}
 if(a.type==='extract'){const item=s.sites[s.node].find(i=>i.id===g.selected&&!i.taken);if(!item)throw Error('Select something to recover.');if(PARTS[item.type]&&slots(s)>=7)throw Error('Parts locker full.');const method=a.method||a.id||'quiet',duration=(method==='force'?4:11)+(hurt(s)?3:0);g.player.hiding=false;g.phase='working';g.working={type:'extract',id:item.id,method,duration,elapsed:item.progress*duration};g.notice=method==='force'?'Fast and loud. This can hurt.':'Freeing the bracket. Taking the part. Watch the gate.';if(method==='force')schedulePatrol(s);}
 if(a.type==='hide'){g.working=null;g.player.hiding=true;g.phase='explore';g.notice='Hidden behind the bus. They will seal the yard when they leave. You keep whatever is already in the van.';}
 if(a.type==='cancelWork'){g.working=null;g.phase='explore';g.notice='Tools down. The work stays in place.';}
 if(a.type==='exitSite'){g.working=null;g.phase='exit';if(g.patrol.state!=='absent'){s.threat.relief=32;g.patrol.state='gone';s.siteMemory[s.node]={sealed:true};}g.notice='Everyone back in the van. Keep moving.';saveSite(s);}
 return true;}
export function updateSalvage(s,dt){const g=s.activity;if(['intercept','exit'].includes(g.phase))return;g.elapsed+=dt;
 if(g.working){const work=g.working,item=s.sites[s.node].find(i=>i.id===work.id);work.elapsed+=dt;item.progress=Math.min(1,work.elapsed/work.duration);if(work.elapsed>=work.duration)extract(s,item,work.method);}
 if(g.elapsed>=22&&g.patrol.state==='absent'&&(s.node==='yard'||s.threat.relief<=0))schedulePatrol(s);
 const p=g.patrol;p.elapsed+=dt;
 if(p.state==='warning'&&p.elapsed>=12){p.state='watch';p.elapsed=0;g.notice='The front gate is blocked. They are checking the machines. Ten seconds to get out or hide.';}
 if(p.state==='watch'&&p.elapsed>=8){p.state='search';p.elapsed=0;g.notice='The officer enters the shed. Hide or leave. They are sealing this site.';}
 if(p.state==='search'){p.seen=Math.max(0,p.seen+(g.player.hiding?-dt:dt*.45));if(p.seen>=1){g.phase='intercept';g.working=null;g.notice='“Mercer household. Your return order is active.” The officer has the van’s plate.';s.threat.identified=true;s.threat.heat=Math.max(1,s.threat.heat);}else if(p.elapsed>=9){s.siteMemory[s.node]={sealed:true};g.phase='exit';p.state='gone';s.threat.relief=32;g.notice='They seal the workshop and leave. You slip out with the supplies already recovered.';}}
 saveSite(s);}
