import {VERSION,TITLE,ITEMS,PARTY,NODES,EDGES,EVENTS,OFFERS,WORK_PLANS,nodeById,itemById} from './content.js?v=0.2.0';
import {newGame,act,advance,loadCampaign,saveCampaign,snapshot,usedSlots,timeLabel,currentDay,travelQuote,choiceStatus,serviceQuote,housingStatus,rounded} from './simulation.js?v=0.2.0';
import {drawScene,portrait,itemIcon,artReady,artStatus,sceneName} from './art.js?v=0.2.0';
const $=s=>document.querySelector(s);
const loaded=loadCampaign(localStorage);let state=loaded.state||newGame(42);let active=false;let hasJourney=!!loaded.state;let overlay=null;let lastFocus=null;let manual=false;let artTime=0;let selectedItem=null;let selectedOffer=null;let savedWarning=false;let sound=false;let audioContext=null;let toastTimer;let lastSave=0;let renderVersion=0;
const icons=Object.fromEntries(ITEMS.map(i=>[i.id,itemIcon(i.id)]));
const money=n=>'$'+Math.round(n).toLocaleString('en-US');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const initials=id=>id[0].toUpperCase()+id.slice(1);
const attrs=(type,id='',extra='')=>`data-action="${type}" data-id="${id}" data-rev="${state.revision}" ${extra}`;
const button=(label,type,id='',kind='primary',extra='')=>`<button class="${kind}" ${attrs(type,id,extra)}>${label}${kind==='primary'?'<span class="arrow">↗</span>':''}</button>`;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),4000);}
function persist(){try{saveCampaign(localStorage,state);}catch{if(!savedWarning){toast('This browser could not save. Keep this tab open to finish the journey.');savedWarning=true;}}}
function tone(kind='choice'){if(!sound)return;try{audioContext||=new AudioContext();audioContext.resume();const notes=kind==='ending'?[196,246.94,293.66,392]:kind==='pack'?[261.63,329.63]:[293.66];for(let i=0;i<notes.length;i++){const o=audioContext.createOscillator(),g=audioContext.createGain(),at=audioContext.currentTime+i*.085;o.type='sine';o.frequency.value=notes[i];g.gain.setValueAtTime(0,at);g.gain.linearRampToValueAtTime(.035,at+.012);g.gain.exponentialRampToValueAtTime(.0001,at+.65);o.connect(g).connect(audioContext.destination);o.start(at);o.stop(at+.7);}}catch{}}
function commit(action){const previous=state.mode;const r=act(state,action);if(!r.ok){toast(r.error);return false;}state=r.state;if(state.mode==='ending')tone('ending');else tone(action.type==='pack'?'pack':'choice');persist();if(state.mode!==previous)$('#panel').scrollTop=0;render();return true;}
function home(){return `<span class="eyebrow">A ROAD THROUGH THE AGE OF ACCESS</span><h1>The Last<br>Affordable<br><em>Place.</em></h1><p class="lede">Your home is a subscription. Your access just expired.<br>Out past the dead service stations, a town needs people who still know how to fix things.</p><div class="signal"><strong>“OWN NOTHING. STAY HAPPY.”</strong>CONTINUUM LIVING · ANNUAL RENEWAL REQUIRED</div><div class="intro-rule"></div><p class="fine">Keep the van running. Keep your people close.<br>Find a place you can afford to stay.</p><div class="button-stack">${hasJourney?button(`Continue · ${nodeById(state.node).name}`,'resume'):''}${button(hasJourney?'Start a different journey':'Pack the van','new','',hasJourney?'secondary':'primary')}</div><div class="people-strip">${PARTY.map(p=>portrait(p.id)).join('')}${portrait('miso')}<small>Four people & Miso the dog.<br>A life worth carrying.</small></div><div class="intro-notes"><span>◷ A short complete journey</span><span>↗ Touch & controller</span><span>▤ Saves as you go</span></div>${loaded.recovered?'<p class="save-note">An interrupted save was recovered where possible.</p>':''}`;}
function packing(){const used=usedSlots(state);const item=ITEMS.find(i=>i.id===selectedItem);return `<span class="chapter-number">00 / THE THINGS WE TAKE</span><div class="packing-intro"><h2>Pack your<br>life.</h2><div class="slot-count">${used}<span> / 6 slots</span></div></div><p class="body">Choose what comes with you. Tap an item to pack or leave it. People, food, and safety gear are already aboard.</p><div class="cargo-grid">${ITEMS.map(i=>`<button class="cargo ${state.cargo.includes(i.id)?'packed':''}" ${attrs('pack',i.id)} aria-pressed="${state.cargo.includes(i.id)}" aria-label="${esc(i.name)}, ${i.slots} slots. ${esc(i.desc)}"><img src="${icons[i.id]}" alt=""><span><strong>${i.name}</strong><small>${i.owner} · ${i.slots} slot${i.slots>1?'s':''}</small></span><span class="check">${state.cargo.includes(i.id)?'✓':'+'}</span></button>`).join('')}</div><div class="item-detail">${item?`<strong>${esc(item.name)}.</strong> ${esc(item.desc)}`:'Useful things open doors. Familiar things make a room feel like yours. You can’t bring them all.'}</div><div class="packing-slots" aria-label="${used} of six slots occupied">${Array.from({length:6},(_,i)=>`<span class="${i<used?'filled':''}"></span>`).join('')}</div><div class="packing-bottom"><p class="fine">Leaving a little space is a choice, too.</p>${button('Start the engine','depart')}</div>`;}
function eventView(){const e=EVENTS[state.event];return `<span class="chapter-number">${esc(e.eyebrow)}</span><h2>${esc(e.title)}</h2><p class="body">${esc(e.body)}</p><div class="speaker">${portrait(e.speaker)}<blockquote>${esc(e.quote)}<small>${initials(e.speaker)}</small></blockquote></div><div class="choices">${e.choices.map((c,i)=>{const v=choiceStatus(state,c);let detail=c.detail;if(c.effect.completeContract&&state.contract)detail=`${state.contract.hours} hours · ${money(state.contract.pay)} on completion · ${state.contract.actor} uses ${state.contract.energy} energy.`;return `<button class="choice" ${attrs('choice',c.id,`data-event="${e.id}" ${v.ok?'':'disabled'}`)}><span class="choice-index">${i+1}</span><span><strong>${esc(c.label)}</strong><small>${esc(detail)}</small>${!v.ok?`<small class="blocked">${esc(v.reason)}</small>`:''}</span></button>`;}).join('')}</div>`;}
function receiptView(){const r=state.receipt;return `<span class="result-stamp">A PAGE IN THE JOURNAL</span><h2>${esc(r.title)}</h2><p class="body">${esc(r.body)}</p><div class="change-strip">${esc(r.changes)}</div><p class="fine">Written into your road journal.</p><div class="button-stack">${button('Carry on','continue')}</div>`;}
function drivers(){return `<span class="eyebrow">WHO’S TAKING THE WHEEL?</span><div class="driver-strip">${PARTY.slice(0,3).map(p=>`<button class="driver ${state.driver===p.id?'selected':''}" ${attrs('driver',p.id)} aria-pressed="${state.driver===p.id}">${portrait(p.id)}<span><strong>${p.name}</strong><small>${Math.round(state.energy[p.id])} energy</small></span></button>`).join('')}</div>${state.mode==='map'?`<div class="pace" aria-label="Travel pace">${[['scenic','Take it easy'],['steady','Steady'],['brisk','Make time']].map(([id,label])=>`<button class="${state.pace===id?'selected':''}" ${attrs('pace',id)} aria-pressed="${state.pace===id}">${label}</button>`).join('')}</div>`:''}`;}
function routes(){return EDGES.filter(e=>e.from===state.node).map(e=>{const q=travelQuote(state,e.id);return `<button class="route" ${attrs('travel',e.id,q.error?'disabled':'')}><span class="route-top">${esc(e.label)}<span>↗</span></span><span class="route-meta"><span>${q.miles} mi</span><span>${rounded(q.hours)}h</span><span>${rounded(q.fuel)} gal</span><span>−${Math.ceil(q.energy)} energy</span></span><p>${esc(e.desc)}</p><p>${esc(q.forecast)}</p>${q.error?`<span class="blocked">${esc(q.error)}</span>`:''}</button>`;}).join('');}
function mapView(){return `<span class="chapter-number">THE ROAD AHEAD</span><h2>${state.node==='R07'?'Choose your destination.':'Choose your road.'}</h2>${state.flags.workPromise==='open'&&state.node==='R04'?'<div class="promise">Dani remembers the festival plan. Take the work road, or talk through a change in Supplies.</div>':''}${drivers()}<div class="routes">${routes()}</div><div class="section-line fine">Need fuel, food, or a break? <button class="text-button" ${attrs('supplies')}>Open supplies</button><br>The arrival reserve is ${money(state.reserve)} of your current cash.</div>`;}
function travelView(){const q=state.travel;const banter=['Jules: “The route planner wants a renewal. The paper map remains stubbornly free.”','Max: “Do you think anyone is still watching all those cameras?”','Dani: “That rattle’s in B-flat. At least something is staying in tune.”','Rowan: “Oil pressure is holding. One thing at a time.”'][Number(q.id.slice(1))%4];return `<span class="chapter-number">${esc(q.forecast.toUpperCase())}</span><h2 class="travel-title">${esc(nodeById(q.to).name)}<br>is up ahead.</h2><p class="body">${esc(nodeById(q.from).name)} → ${esc(nodeById(q.to).name)}</p><div class="travel-meter"><div id="travel-fill" style="width:${Math.min(100,q.elapsed/q.duration*100)}%"></div></div><div class="travel-details"><span>${q.miles} miles</span><span>${rounded(q.hours)} hours</span><span>${initials(q.driver)} driving</span></div><p class="travel-banter">${esc(banter)}</p><p class="fine">Watch the road for a moment. Your journey is saved as you go.</p><div class="button-stack">${button('Arrive at the next stop','skipTravel','','secondary')}</div>`;}
function offersView(){let offers=OFFERS.filter(o=>o.node===state.node||o.id==='bridge');let o=offers.find(o=>o.id===selectedOffer)||offers[0];selectedOffer=o.id;const status=housingStatus(state,o);const plan=WORK_PLANS.find(p=>p.id===state.plan);const bridge=o.id==='bridge';return `<span class="chapter-number">A DOOR WE GET TO CHOOSE</span><h2>Find your home.</h2><div class="offer-tabs">${offers.map(x=>button(x.type,'offer',x.id,x.id===o.id?'selected':'')).join('')}</div><div class="offer-info"><span class="eyebrow">${o.type}</span><h3>${esc(o.name)}</h3><p>${esc(o.desc)}</p><p style="margin-top:10px"><strong>${esc(o.tradeoff)}</strong></p></div>${!bridge?`<span class="eyebrow">NEXT MONTH’S WORK</span><div class="plan-pick">${WORK_PLANS.map(p=>`<button class="${state.plan===p.id?'selected':''}" ${attrs('plan',p.id,p.requiresJob&&state.contract?.status!=='fulfilled'?'disabled':'')}><strong>${p.name} · ${money(p.income)}/month</strong><small>${p.desc}${p.requiresJob&&state.contract?.status!=='fulfilled'?' Needs the completed festival job.':''}</small></button>`).join('')}</div>`:'<p class="fine">The group has arranged a follow-up housing appointment in seven days and access to the local job board. Long-term housing remains unresolved.</p>'}<div class="budget"><div><span>${bridge?'Fourteen-night stay':'Move-in cost'}</span><strong>${money(bridge?Math.min(120,state.cash):o.moveIn)}</strong></div>${!bridge?`<div><span>Housing + utilities / month</span><span>${money(o.monthly)}</span></div><div><span>Other essentials / month</span><span>${money(o.other)}</span></div><div><span>Planned income / month</span><span>${money(plan.income)}</span></div><div class="total"><span>Left each month</span><strong>${money(plan.income-o.monthly-o.other)}</strong></div>`:''}<div><span>Cash left after moving in</span><strong>${money(state.cash-(bridge?Math.min(120,state.cash):o.moveIn))}</strong></div></div>${bridge&&state.cash<120?`<p class="fine">The bridge fund covers ${money(120-state.cash)} of the stay. This support is part of the temporary plan.</p>`:''}${!state.flags.consulted&&!bridge?button('Discuss this with the group','consultHome','','secondary'):''}${!status.ok?`<p class="warning">${esc(status.reason)}</p>`:''}${button(bridge?'Take a little breathing room':'Choose this home','confirmHome',o.id,'primary',status.ok?'':'disabled')}${state.node==='R08'?`<div class="section-line"><p class="fine">You can also keep looking.</p>${drivers()}<div class="routes" style="margin-top:12px">${routes()}</div></div>`:''}`;}
function endingView(){const e=state.ending;return `<span class="result-stamp">${e.id==='bridge'?'A PAUSE WITH A PLAN':'THIS IS A BEGINNING'}</span><h2 class="ending-head">${esc(e.name)}.</h2><p class="body">${e.id==='bridge'?'The long-term home is still ahead. For tonight, there is a safe room, a follow-up appointment, and time to think.':'The boiler knocks. Somebody has left a box of spare parts by the door. There is work to do in the morning. For tonight, the key is in your pocket and everyone is inside.'}</p><div class="budget"><div><span>${Math.round(state.miles).toLocaleString()} miles · ${currentDay(state)} fictional days</span><strong>${money(state.cash)} left</strong></div>${e.id!=='bridge'?`<div class="total"><span>Left each month</span><strong>${money(e.monthlyMargin)}</strong></div>`:'<div><span>Next appointment</span><strong>In seven days</strong></div>'}</div>${e.callbacks.slice(0,3).map(s=>`<p class="ending-callback">${esc(s)}</p>`).join('')}<div class="button-stack">${button('Pack differently. Find another life.','new')}${button('Read our road journal','journal','','secondary')}</div><p class="fine" style="margin-top:15px">Your finished journey is saved until you choose to start another.</p>`;}
function routeDiagram(){const seen=new Set(state.visited);return `<svg viewBox="25 38 980 283" role="img" aria-label="Roads from the Pacific Northwest to Morrow and Cal’s town">${EDGES.map(e=>{const a=nodeById(e.from),b=nodeById(e.to),visited=seen.has(e.from)&&seen.has(e.to);return `<path d="M${a.x} ${a.y} C${(a.x+b.x)/2} ${a.y},${(a.x+b.x)/2} ${b.y},${b.x} ${b.y}" fill="none" stroke="${visited?'#c7a572':'#718c80'}" stroke-width="${visited?5:2}" ${visited?'':'stroke-dasharray="5 6"'}/>`;}).join('')}${NODES.map(n=>`<circle cx="${n.x}" cy="${n.y}" r="${n.id===state.node?12:6}" fill="${n.id===state.node?'#e1ad73':seen.has(n.id)?'#9eb9a2':'#324842'}" stroke="#8fa89b" stroke-width="2"/><text x="${n.x}" y="${n.y+(n.y>200?29:-22)}" font-size="19" text-anchor="middle" fill="#e2ddcc" font-family="Chakra Petch">${{R00:'Start',R01:'The pass',R02:'Plateau',R03:'Omar’s',R04:'Bea’s',R05:'Repair fair',R06:'Juniper',R07:'The lakes',R08:'Cal’s',R09:'Morrow',R10:'Bridge'}[n.id]}</text>`).join('')}</svg>`;}
function routeMap(){showDialog('The road ahead.',`<p>${esc(nodeById(state.node).name)} · ${Math.round(state.miles).toLocaleString()} miles traveled</p><div class="map-scroll">${routeDiagram()}</div><p class="fine">Scroll across the map. Gold roads show where you’ve been.</p>`,true);requestAnimationFrame(()=>{const box=document.querySelector('.map-scroll');if(box)box.scrollLeft=Math.max(0,nodeById(state.node).x-box.clientWidth/2);});}
function renderMap(){const visible=active&&['map','travel'].includes(state.mode);$('.stage').classList.toggle('has-map',visible);$('#roadmap').hidden=!visible;if(!visible)return;$('#roadmap').innerHTML=`<div class="map-summary"><span><strong>${Math.round(state.miles).toLocaleString()} miles traveled</strong><small>${state.visited.length} stop${state.visited.length===1?'':'s'} on your journey</small></span>${button('Route map','routeMap','','secondary')}</div>`;}
function renderResources(){const box=$('#resources');box.hidden=!active;if(!active)return;box.innerHTML=`${[['TIME',timeLabel(state),''],['CASH',money(state.cash),state.mode==='ending'?'':`${money(state.reserve)} reserved`],['FUEL',rounded(state.fuel)+' gal',''],['FOOD',state.food.toFixed(1)+' days',''],['VAN',Math.round(state.condition)+'%','']].map(([name,value,sub],i)=>`<div class="resource ${i===1&&state.mode!=='ending'&&state.cash<1000||i===2&&state.fuel<18||i===3&&state.food<.6||i===4&&state.condition<35?'low':''}"><small>${name}</small><strong>${value}</strong>${sub?`<span class="sub">${sub}</span>`:''}</div>`).join('')}<div class="resource-actions">${button('The group','party','','')}${button('Supplies','supplies','','',state.mode==='packing'||state.mode==='travel'||state.mode==='ending'||state.mode==='receipt'?'disabled':'')}</div>`;}
function render(){renderVersion++;const previousFocus=document.activeElement;const focusKey=previousFocus?.dataset?.action;const focusId=previousFocus?.dataset?.id;$('#layout').classList.toggle('playing',active);$('#pause').hidden=!active;$('#journal').hidden=!active;renderResources();const views={packing,event:eventView,receipt:receiptView,map:mapView,travel:travelView,offers:offersView,ending:endingView};$('#panel').innerHTML=active?views[state.mode]():home();const n=nodeById(state.node);$('#chapter').textContent=active?`${timeLabel(state)} / ${n.subtitle.toUpperCase()}`:'PACIFIC NORTHWEST → THE GREAT LAKES';$('#stamp').innerHTML=state.mode==='ending'?'ENOUGH<br>IS A<br>BEGINNING':'OWNER<br>MAINTAINED';$('#scene-caption').innerHTML=active?`<span class="eyebrow">${state.mode==='ending'?'THE PLACE WE CHOOSE':n.subtitle.toUpperCase()}</span><p>${state.mode==='ending'?'Some things are<br>still worth keeping.':state.mode==='packing'?'What can’t they<br>take back?':esc(n.name)+'.<br>One stop closer.'}</p>`:'<span class="eyebrow">FOUR PEOPLE. ONE DOG. ONE WAY FORWARD.</span><p>The future broke down.<br>You kept the keys.</p>';$('#footer-left').textContent=active?`${state.cargo.length} OBJECTS / ${state.journal.length} JOURNAL ENTRIES / ${state.flags.workPromise==='fulfilled'?'ONE PROMISE KEPT':'ONE WAY FORWARD'}`:'NO REMOTE LOCK. NO RENEWAL. JUST KEEP IT RUNNING.';renderMap();drawScene($('#scene'),state,artTime,!active);if(focusKey&&!overlay){const b=[...document.querySelectorAll('button[data-action]')].find(b=>b.dataset.action===focusKey&&b.dataset.id===focusId&&!b.disabled);b?.focus({preventScroll:true});}}
function showDialog(title,content,wide=false){lastFocus=document.activeElement;overlay=title;const box=$('#overlay');box.hidden=false;box.innerHTML=`<section role="dialog" aria-modal="true" aria-label="${esc(title)}" class="dialog ${wide?'wide':''}"><div class="dialog-top"><h2>${esc(title)}</h2><button class="close" data-action="close" aria-label="Close dialog">×</button></div>${content}</section>`;box.querySelector('button')?.focus();persistIfActive();}
function closeDialog(){overlay=null;$('#overlay').hidden=true;$('#overlay').innerHTML='';lastFocus?.isConnected&&lastFocus.focus({preventScroll:true});}
function persistIfActive(){if(active)persist();}
function pause(){if(!active)return;showDialog('The road can wait.',`<p>Your journey is saved. Time only moves when you travel or make a choice.</p><div class="button-stack">${button('Back to the road','close')}${button('Read the journal','journal','','secondary')}${button('Back to the opening','title','','secondary')}</div><p class="fine" style="margin-top:18px">${timeLabel(state)} · ${esc(nodeById(state.node).name)} · ${money(state.cash)}</p>`);}
function supplies(){const ids=['fuel','food','rest','vanrest','repair','job','call'];if(state.flags.workPromise==='open')ids.push('consult');showDialog('Keep it running.',`<p style="margin-bottom:16px">${money(state.cash)} on hand. The ${money(state.reserve)} arrival reserve is included in that total.</p><div class="supply-list">${ids.map(id=>{const q=serviceQuote(state,id);return `<button ${attrs('service',id,q.error?'disabled':'')}><strong>${esc(q.label)}<span>${q.cash<0?'−'+money(-q.cash):q.cash>0?'+'+money(q.cash):'No charge'}</span></strong><small>${esc(q.error||q.desc)}</small><small>${rounded(q.hours)}h${q.energy?' · +'+q.energy+' energy':''}</small></button>`;}).join('')}</div><div class="section-line"><p>Out of room to maneuver? A temporary stay can give the group a safe next step.</p>${button('Discuss a bridge stay','confirmBridge','','secondary')}</div>`);}
function journal(){showDialog('The things that stayed.',`<p>Four people, one dog, and ${state.journal.length} pages of decisions.</p>${state.journal.length?state.journal.map(e=>`<article class="journal-entry"><small>DAY ${e.day} / ${esc(nodeById(e.node).name.toUpperCase())}</small><h3>${esc(e.title)}</h3><p>${esc(e.text)}</p></article>`).join(''):'<p style="margin-top:22px">The first page is waiting. Pack the van.</p>'}`,true);}
function party(){showDialog('The people in the van.',PARTY.map(p=>`<div class="party-member">${portrait(p.id)}<div><h3>${p.name}</h3><small>${p.role}${state.energy[p.id]!==undefined?' · '+Math.round(state.energy[p.id])+' energy':''}</small><p>“${esc(p.line)}”</p></div></div>`).join('')+`<div class="party-member">${portrait('miso')}<div><h3>Miso</h3><p>Dog. Fixed safe seat. Suspicious of automatic bins. Extremely ready for dinner.</p></div></div>`,true);}
function help(){showDialog('The road manual.',`<p><strong>1. Pack six cargo slots.</strong> Tools open repairs; the sound kit unlocks a bigger job. Keepsakes come back in your ending.</p><p style="margin-top:13px"><strong>2. Choose a route and driver.</strong> The road card shows the entire cost before you go. Steady is a good start. Switch drivers or rest when energy is low.</p><p style="margin-top:13px"><strong>3. Make useful stops.</strong> Supplies has fuel, food, rest, and bounded work. A job offer pays only when you complete it.</p><p style="margin-top:13px"><strong>4. Choose a home you can sustain.</strong> Read move-in and next-month terms. The shared home and friend-town home are full successes too.</p><p style="margin-top:13px">Touch: tap the choices. Controller: stick or D-pad moves focus, south button chooses, east button goes back, Start pauses. Keyboard: arrows/Tab and Enter; Escape pauses; F toggles fullscreen.</p><p class="section-line">This is a fictional 2032, with an authored route and invented costs. First browser playtest; native Apple production and physical-device performance testing come later. No account, payments, live listings, or online connection is required after this game has loaded.</p>`);}
function startNew(){state=newGame(hasJourney?(state.seed+7919)>>>0:42);active=true;hasJourney=true;selectedOffer=null;selectedItem=null;closeDialog();manual=false;persist();render();$('#panel').scrollTop=0;window.scrollTo({top:0});}
function handle(el){const type=el.dataset.action,id=el.dataset.id;const revision=Number(el.dataset.rev);if(type==='new'){if(hasJourney&&state.mode!=='ending'){showDialog('Take a different road?',`<p>Starting a new journey replaces the current autosave. You’re at ${esc(nodeById(state.node).name)}, with ${money(state.cash)}.</p><div class="button-stack">${button('Keep this journey','close')}${button('Start a new journey','newConfirmed','','secondary')}</div>`);}else startNew();return;}
 if(type==='newConfirmed'){startNew();return;}if(type==='resume'){active=true;closeDialog();render();return;}if(type==='close'){closeDialog();return;}if(type==='title'){active=false;closeDialog();render();return;}if(type==='journal'){journal();return;}if(type==='routeMap'){routeMap();return;}if(type==='party'){party();return;}if(type==='supplies'){supplies();return;}if(type==='offer'){selectedOffer=id;render();return;}
 if(type==='confirmHome'){const o=OFFERS.find(o=>o.id===id);const q=housingStatus(state,o);if(!q.ok){toast(q.reason);return;}showDialog('The door we choose.',`<p>Agree to <strong>${esc(o.name)}</strong> for ${money(q.cost)}. You will have ${money(q.remaining)} left.${o.id==='bridge'?' This ends the chapter with a temporary stay and a next step.':' The planned monthly margin is '+money(q.monthlyMargin)+'.'}</p><p style="margin-top:14px">The group has read the terms together. Ready to begin?</p><div class="button-stack">${button('This is our next chapter','accept',id)}${button('Look at the terms again','close','','secondary')}</div>`);return;}
 if(type==='confirmBridge'){showDialog('A pause with a plan.',`<p>End this journey with a fourteen-night temporary stay and a follow-up housing appointment. It costs up to $120; an emergency bridge fund covers any gap. Long-term housing will remain unresolved.</p><div class="button-stack">${button('Look at the bridge terms','bridge')}${button('Keep working on this journey','close','','secondary')}</div>`);return;}
 if(type==='pack')selectedItem=id;
 if(type==='service'||type==='accept'||type==='bridge')closeDialog();
 commit({type,id,event:el.dataset.event,revision:Number.isFinite(revision)?revision:undefined});
}
document.addEventListener('click',e=>{const el=e.target.closest('button[data-action]');if(el&&!el.disabled){handle(el);}});
$('#pause').onclick=pause;$('#journal').onclick=journal;$('#help').onclick=help;$('#brand').onclick=e=>{e.preventDefault();if(active)pause();};$('#sound').onclick=()=>{sound=!sound;$('#sound').textContent=sound?'Sound on':'Sound off';$('#sound').setAttribute('aria-label',sound?'Turn sound off':'Turn sound on');tone();};
function focusables(){return [...document.querySelectorAll(overlay?'#overlay button:not(:disabled)':'#app button:not(:disabled),#app a')].filter(e=>e.offsetParent!==null&&!e.hidden);}
function moveFocus(direction){const bs=focusables();if(!bs.length)return;const i=bs.indexOf(document.activeElement);const n=(i+direction+bs.length)%bs.length;document.querySelectorAll('.gamepad-focus').forEach(e=>e.classList.remove('gamepad-focus'));bs[n].classList.add('gamepad-focus');bs[n].focus();bs[n].scrollIntoView({block:'nearest',inline:'nearest'});}
document.addEventListener('keydown',e=>{if(['ArrowDown','ArrowRight','ArrowUp','ArrowLeft'].includes(e.key)){e.preventDefault();moveFocus(['ArrowDown','ArrowRight'].includes(e.key)?1:-1);}if(e.key==='Escape'){e.preventDefault();overlay?closeDialog():pause();}if(e.key.toLowerCase()==='f'){if(document.fullscreenElement)document.exitFullscreen?.();else document.documentElement.requestFullscreen?.().catch(()=>{});}if(e.key==='Tab'&&overlay){const bs=focusables(),i=bs.indexOf(document.activeElement);if(e.shiftKey&&i<=0){e.preventDefault();bs.at(-1)?.focus();}else if(!e.shiftKey&&i===bs.length-1){e.preventDefault();bs[0]?.focus();}}});
let padPrevious={a:false,b:false,start:false,dir:0};let lastMove=0;
function readPad(now){const pad=navigator.getGamepads?.()?.find?.(p=>p?.connected);if(!pad){padPrevious={a:false,b:false,start:false,dir:0};return;}const a=!!pad.buttons[0]?.pressed,b=!!pad.buttons[1]?.pressed,start=!!pad.buttons[9]?.pressed;const right=pad.buttons[13]?.pressed||pad.buttons[15]?.pressed||pad.axes[1]>.55||pad.axes[0]>.55;const left=pad.buttons[12]?.pressed||pad.buttons[14]?.pressed||pad.axes[1]<-.55||pad.axes[0]<-.55;const dir=right?1:left?-1:0;if(dir&&(dir!==padPrevious.dir||now-lastMove>260)){moveFocus(dir);lastMove=now;}if(a&&!padPrevious.a){const el=document.activeElement;if(el?.tagName==='BUTTON')el.click();else focusables()[0]?.focus();}if(b&&!padPrevious.b)overlay?closeDialog():pause();if(start&&!padPrevious.start)overlay?closeDialog():pause();padPrevious={a,b,start,dir};}
function tick(dt){if(!active||overlay)return;const previous=state.mode;state=advance(state,dt);artTime+=dt;if(state.mode!==previous){persist();render();}else if(state.mode==='travel'){const fill=$('#travel-fill');if(fill)fill.style.width=Math.min(100,state.travel.elapsed/6*100)+'%';}}
let previous=performance.now(),lastDraw=0;function frame(now){const dt=Math.min(.08,(now-previous)/1000);previous=now;readPad(now);if(!manual&&!document.hidden)tick(dt);if(!active&&!manual)artTime+=dt*.3;if(!document.hidden&&now-lastDraw>=32){drawScene($('#scene'),state,artTime,!active);lastDraw=now;}if(active&&state.mode==='travel'&&!overlay&&now-lastSave>1000){persist();lastSave=now;}requestAnimationFrame(frame);}requestAnimationFrame(frame);
window.advanceTime=async ms=>{manual=true;tick(Math.min(30000,Math.max(0,Number(ms)))/1000);drawScene($('#scene'),state,artTime,!active);await new Promise(requestAnimationFrame);};
window.render_game_to_text=()=>JSON.stringify({...snapshot(state),art:{...artStatus(),scene:sceneName(state)},typography:{family:'Chakra Petch',ready:document.fonts.check('400 18px \"Chakra Petch\"')&&document.fonts.check('700 32px \"Chakra Petch\"')},mode:active?state.mode:'intro',overlay,muted:!sound,saveUnavailable:savedWarning,visibleActions:focusables().filter(b=>b.dataset.action).map(b=>({type:b.dataset.action,id:b.dataset.id,label:b.textContent.trim().slice(0,80)}))});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&active){persist();if(!overlay&&state.mode==='travel')pause();}});window.addEventListener('pagehide',persistIfActive);window.addEventListener('resize',()=>drawScene($('#scene'),state,artTime,!active));render();
// Install the offline shell only on a hosted origin. Local iterations always use fresh files.
if('serviceWorker' in navigator&&!['localhost','127.0.0.1'].includes(location.hostname))navigator.serviceWorker.register('./sw.js').catch(()=>{});

window.artReady=Promise.all([artReady,document.fonts.load('400 18px \"Chakra Petch\"'),document.fonts.load('500 16px \"Chakra Petch\"'),document.fonts.load('700 32px \"Chakra Petch\"')]);window.artReady.then(()=>drawScene($('#scene'),state,artTime,!active));
