import {VERSION,ITEMS,EDGES,EVENTS,NODE_EVENTS,OFFERS,WORK_PLANS,nodeById,itemById} from './content.js';
export const SAVE_KEY='common-road-save-v1';
export const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
export const rounded=x=>Math.round(x*100)/100;
const copy=x=>structuredClone(x);
export function newGame(seed=42){return {version:VERSION,schema:1,seed:seed>>>0,revision:0,mode:'packing',node:'R00',visited:['R00'],hours:8,cash:1900,reserve:1000,fuel:45,food:4,condition:85,energy:{rowan:80,jules:80,dani:80},cargo:[],flags:{viewDay:10,workPromise:'none'},driver:'rowan',pace:'steady',done:[],queue:[],event:null,receipt:null,contract:null,travel:null,journal:[],transactions:[],serviceUses:[],plan:'maintenance',ending:null,miles:0};}
export function usedSlots(s){return s.cargo.reduce((v,id)=>v+itemById(id).slots,0);}
export function currentDay(s){return Math.floor(s.hours/24)+1;}
export function timeLabel(s){const h=Math.floor(s.hours%24);return `Day ${currentDay(s)} · ${String(h).padStart(2,'0')}:${String(Math.floor(s.hours%1*60)).padStart(2,'0')}`;}
export function forecast(s,edge){const n=(s.seed*17+Number(edge.id.slice(1))*13)%7;return n===0?{label:'Rain on the pass',fuel:1.06,hours:.4}:n===2?{label:'Roadworks, posted ahead',fuel:1,hours:.5}:{label:'Clear road',fuel:1,hours:0};}
export function travelQuote(s,id){const e=EDGES.find(e=>e.id===id);if(!e||e.from!==s.node)return {error:'That road does not leave this stop.'};const w=forecast(s,e);const p={steady:[1,1,1,1],scenic:[1.18,.94,.9,.9],brisk:[.87,1.12,1.24,1.35]}[s.pace];const hours=e.hours*p[0]+w.hours;const fuel=e.miles/22*p[1]*w.fuel*(s.condition<40?1.08:1);const energy=hours*5.3*p[2];const wear=e.miles/120*p[3];const q={...e,hours,fuel,energy,wear,food:hours/24,forecast:w.label,driver:s.driver,error:null};if(s.fuel+1e-8<fuel)q.error=`Need ${rounded(fuel-s.fuel)} more gallons. Refuel at this stop.`;else if(s.food+1e-8<q.food)q.error='Buy provisions before this leg.';else if(s.energy[s.driver]-energy<8)q.error='This driver needs rest. Swap drivers or stop for the night.';else if(s.condition-wear<15)q.error='The van needs repair before this leg.';return q;}
function hours(s,h){s.hours+=h;s.food=clamp(s.food-h/24,0,8);}
function energy(s,n){for(const id of Object.keys(s.energy))s.energy[id]=clamp(s.energy[id]+n,0,100);}
function log(s,title,text){s.journal.push({day:currentDay(s),node:s.node,title,text});}
function availableEvent(s,id){return !s.done.includes(id)&&!(id==='chair'&&!s.cargo.includes('I05'))&&!(id==='invoice'&&s.contract?.status!=='accepted');}
function nextScene(s){s.receipt=null;while(s.queue.length){const id=s.queue.shift();if(availableEvent(s,id)){s.event=id;s.mode='event';return;}}s.event=null;s.mode=['R08','R09','R10'].includes(s.node)?'offers':'map';}
function arrive(s){s.node=s.travel.to;s.visited.push(s.node);s.travel=null;s.queue=[...(NODE_EVENTS[s.node]||[])];nextScene(s);}
function effectQuote(s,e){let q={...e};if(e.completeContract){if(!s.contract||s.contract.status!=='accepted')return {error:'There is no open contract.'};q={...q,cash:s.contract.pay,hours:s.contract.hours,actor:s.contract.actor,actorEnergy:-s.contract.energy};}if((q.cash||0)+s.cash<0)return {error:`Need $${Math.ceil(-q.cash-s.cash)} more for this choice.`};if((q.hours||0)/24>s.food+Math.max(0,q.food||0)+1e-8)return {error:'Buy provisions from the Supplies panel first.'};if(q.actor&&s.energy[q.actor]+(q.actorEnergy||0)<0)return {error:`${q.actor} needs rest before this task.`};return q;}
export function choiceStatus(s,choice){if(choice.item&&!s.cargo.includes(choice.item))return {ok:false,reason:`Needs ${itemById(choice.item).name.toLowerCase()}.`};if(choice.actor&&(s.energy[choice.actor]<choice.minEnergy))return {ok:false,reason:`${choice.actor} needs at least ${choice.minEnergy} energy.`};const q=effectQuote(s,choice.effect);return q.error?{ok:false,reason:q.error}:{ok:true,quote:q};}
function applyEffect(s,e){const q=effectQuote(s,e);if(q.error)throw Error(q.error);s.cash+=q.cash||0;const foodBefore=s.food;hours(s,q.hours||0);s.food=clamp(foodBefore+(q.food||0)-(q.hours||0)/24,0,8);s.condition=clamp(s.condition+(q.condition||0),0,100);energy(s,q.energy||0);if(q.actor)s.energy[q.actor]=clamp(s.energy[q.actor]+(q.actorEnergy||0),0,100);Object.assign(s.flags,q.flags||{});if(q.remove)s.cargo=s.cargo.filter(id=>id!==q.remove);if(q.contract){s.contract={id:q.contract,status:'accepted',pay:q.contract==='sound'?180:80,hours:q.contract==='sound'?4:2,actor:q.contract==='sound'?'dani':'rowan',energy:q.contract==='sound'?24:12};s.flags.workPromise='accepted';}if(q.completeContract){s.contract.status='fulfilled';s.flags.workPromise='fulfilled';}if(q.cancelContract){if(s.contract)s.contract.status='cancelled';s.flags.workPromise='cancelled';}return q;}
export function effectsText(q){const v=[];if(q.cash)v.push(`${q.cash>0?'+':'−'}$${Math.abs(q.cash)}`);if(q.hours)v.push(`${rounded(q.hours)}h`);if(q.energy)v.push(`${q.energy>0?'+':''}${q.energy} energy for everyone`);if(q.actorEnergy)v.push(`${q.actor}: ${q.actorEnergy} energy`);if(q.condition)v.push(`+${q.condition} van condition`);if(q.food)v.push(`+${q.food} days of food`);return v.join(' · ')||'No cost. Your choice is remembered.';}
function receipt(s,title,body,changes,back='map'){s.mode='receipt';s.receipt={title,body,changes,back};}
function callback(s,id,choice){
 if(id==='departure')return s.flags.workPromise==='open'?'Dani folds the festival notice into the map. “Thanks. Let’s see if it makes sense when we get there.”':'Jules circles the first stop, not the entire future. “One decision at a time.”';
 if(id==='chair')return s.flags.chairSold?'Max draws the chair before it goes. It still has a page in the new home.':'The chair travels on. Max puts the drawing case beside it.';
 if(id==='invoice')return s.contract?.status==='fulfilled'?`Petra pays the agreed $${s.contract.pay}. Dani labels the cable bag ACTUALLY FINISHED.`:'Petra closes the booking. No invoice, no secret payment. The group has its time back.';
 if(id==='key')return s.flags.remyHelp?'Remy points to the fixed latch. “Still holding.” A small favor has become a familiar face.':'Remy waves. A respectful no did not turn a fellow traveler into an enemy.';
 if(id==='picnic')return s.cargo.includes('I07')?'Max fills a page with the valley and a tiny, overpacked van. There is no price in the corner.':'Max borrows a receipt. On the back: a valley, a van, and four people who stopped to see it.';
 if(id==='repair')return s.flags.repair==='deferred'?`Bea writes ${Math.round(s.condition)}/100 on the inspection. “Watch it. You still have choices.”`:'The engine sounds a little less like an argument. Bea wipes the tools and wishes you a good trip.';
 if(id==='meal')return s.cargo.includes('I03')?'For forty-five minutes, the folding table is a kitchen. Nobody asks whose kitchen.':'The group sits under the trees. Miso remains optimistic about the tomatoes.';
 return {phone:'Mara’s terms are saved with the route. The move-in reserve is still part of your cash, not a second bank account.',home:`The group agrees that ${s.flags.priority} matters. That preference will be remembered; it is not a hidden test.`,bulletin:s.flags.shelfFixed?'The shelf is level. The money is real. Omar adds your name to the non-personalized bulletin board.':'Omar sends you off with a useful contact and directions to the good view.',camp:s.flags.camped?'Everyone sleeps. Even the phone looks a little less certain in the morning.':'Jean tops up the kettle. A short stop can still be a good one.',favor:s.flags.remyHelp?'The latch closes. Remy hands over the promised voucher. You have helped for exactly as long as you agreed.':'You give Remy Bea’s number, and keep your afternoon.',job:s.contract?.status==='accepted'?'The agreement is saved. You will be paid when the next scene’s work is completed.':'Nobody works for imaginary exposure today.',friend:'Cal puts the written terms on the kitchen table. “Now we can have an honest conversation.”',arrival:'The rooms have walls, windows, and ordinary costs. Choose the life that fits the group.'}[id]||'The road carries on. This choice has a place in your journal.';
}
export function housingStatus(s,o){if(o.id==='bridge')return {ok:true,cost:Math.min(120,s.cash),income:0,remaining:s.cash-Math.min(120,s.cash),monthlyMargin:0};if(o.node!==s.node)return {ok:false,reason:'Visit this town first.'};if(!s.flags[o.flag])return {ok:false,reason:'Inspect the terms first.'};if(s.node==='R09'&&currentDay(s)>s.flags.viewDay)return {ok:false,reason:'Call Mara to reschedule the viewing from Supplies.'};if(!s.flags.consulted)return {ok:false,reason:'Discuss the arrangement with the group first.'};const p=WORK_PLANS.find(p=>p.id===s.plan);if(!p)return {ok:false,reason:'Choose a next-month work plan.'};if(p.requiresJob&&s.contract?.status!=='fulfilled')return {ok:false,reason:'This plan needs a completed festival job.'};if(s.cash<o.moveIn)return {ok:false,reason:`Need $${Math.ceil(o.moveIn-s.cash)} more to move in.`};const monthlyMargin=p.income-o.monthly-o.other;if(monthlyMargin<0)return {ok:false,reason:'The next-month plan needs more income.'};return {ok:true,cost:o.moveIn,income:p.income,remaining:s.cash-o.moveIn,monthlyMargin};}
export function endingCallbacks(s){const lines=[];
 if(s.cargo.includes('I05'))lines.push('Grandma’s chair goes by the window. Max sits there to finish the last page.');else if(s.flags.chairSold)lines.push('Max hangs the drawing of Grandma’s chair. Some things arrived another way.');
 if(s.cargo.includes('I06'))lines.push('Jules puts the basil on the sill. The plant has another address.');
 if(s.flags.workPromise==='fulfilled')lines.push('Dani unpacks the cables with a paid invoice tucked inside. The promise became a real job.');else if(s.flags.workPromise==='renegotiated')lines.push('The group changed the work plan together. Dani still has a say in what comes next.');else if(s.flags.workPromise==='open')lines.push('Dani remembers the festival promise that never became a stop. That conversation is still waiting.');else if(s.flags.workPromise==='accepted')lines.push('The festival booking is still open. Dani will call Petra before the next chapter begins.');else if(s.flags.workPromise==='cancelled')lines.push('The festival job was cancelled openly. Dani is working out a different next step.');
 if(s.flags.sharedMeal||s.flags.tableDinner)lines.push('The first meal borrows a recipe from Juniper campground. It already feels a little familiar.');
 if(s.flags.picnic)lines.push('Max’s valley sketch becomes the first thing on the wall. You stopped long enough to bring it here.');
 if(s.flags.shelfFixed)lines.push('Omar sends a photo of the shelf. It is still level. “Good luck with your own place.”');
 if(s.cargo.includes('I01'))lines.push('Rowan opens the tool case. This time, there is no departure deadline.');
 lines.push('Miso circles the new sleeping spot twice and decides it will do.');return lines.slice(0,5);}
export function serviceQuote(s,id){const one=s.serviceUses.includes(`${s.node}:${id}`);const missing=45-s.fuel;const fuelCost=Math.ceil(missing*5-1e-7);const voucher=Math.min(s.flags.voucher||0,fuelCost);const defs={
 fuel:{label:'Fill the tank',cash:-(fuelCost-voucher),hours:.25,fuel:missing,voucher,desc:`${rounded(missing)} gallons at $5. ${voucher?'Uses your $'+voucher+' voucher.':''}`},
 food:{label:'Buy a day of provisions',cash:s.cargo.includes('I04')?-36:-45,hours:.25,food:1,desc:'Food and water for the whole group, for one day.'},
 rest:{label:'Book a basic room',cash:-60,hours:8,energy:65,desc:'Eight hours off the road. Everyone recovers 65 energy.'},
 vanrest:{label:'Rest in the van',cash:0,hours:4,energy:s.cargo.includes('I08')?32:22,desc:'Four hours in a signed safe rest area. Slower recovery, no room charge.'},
 repair:{label:s.cargo.includes('I01')?'Repair with your tools':'Book a van repair',cash:s.cargo.includes('I01')?-25:-100,hours:2,condition:30,desc:'Restore 30 condition before the next leg.'},
 job:{label:'Take the notice-board task',cash:45,hours:2,actor:'rowan',actorEnergy:-8,once:true,desc:'One small local task, once per stop. Earn $45 for two hours.'},
 call:{label:'Call Mara about your viewing',cash:0,hours:.5,desc:'Confirm terms and an appointment at least three days from now.',flags:{verified:true,viewDay:Math.max(14,currentDay(s)+3)}},
 consult:{label:'Talk the work promise through',cash:0,hours:.5,desc:'Agree on a changed route together. No fee and no imaginary payout.',flags:{workPromise:'renegotiated'}},
 };
 const q=defs[id];if(!q)return {error:'Unknown service.'};if(id==='fuel'&&missing<.01)return {...q,error:'The tank is full.'};if(id==='food'&&s.food>7)return {...q,error:'The provision box is full.'};if(id==='repair'&&s.condition>=95)return {...q,error:'The van is already in good condition.'};if(q.once&&one)return {...q,error:'This stop’s task is already complete.'};if(id==='consult'&&s.flags.workPromise!=='open')return {...q,error:'There is no open route promise to renegotiate.'};const checked=effectQuote(s,q);if(checked.error)return {...q,error:checked.error};return q;}
export function act(original,a){if(a.revision!==undefined&&a.revision!==original.revision)return {ok:false,state:original,error:'That choice has already changed. Read the current screen.'};const s=copy(original);try{
 if(s.mode==='ending'&&a.type!=='replay')throw Error('This journey is complete. Start another to make new choices.');
 switch(a.type){
 case 'pack':{if(s.mode!=='packing')throw Error('Packing is closed for this trip.');const i=itemById(a.id);if(!i)throw Error('Unknown cargo.');if(s.cargo.includes(i.id))s.cargo=s.cargo.filter(id=>id!==i.id);else{if(usedSlots(s)+i.slots>6)throw Error('The van has six cargo slots. Leave something before adding this.');s.cargo.push(i.id);}break;}
 case 'depart':if(s.mode!=='packing')throw Error('This journey has already started.');s.queue=['departure'];log(s,'What came with us',s.cargo.map(id=>itemById(id).name).join(', ')||'The essentials, the group, and room for what comes next.');nextScene(s);break;
 case 'choice':{if(s.mode!=='event'||s.event!==a.event)throw Error('That encounter is no longer open.');const e=EVENTS[s.event];const c=e.choices.find(c=>c.id===a.id);if(!c)throw Error('Unknown choice.');const status=choiceStatus(s,c);if(!status.ok)throw Error(status.reason);const q=applyEffect(s,c.effect);s.done.push(e.id);const body=callback(s,e.id,c.id);log(s,e.title,c.label+'. '+body);receipt(s,e.title,body,effectsText(q),'events');break;}
 case 'continue':if(s.mode!=='receipt')throw Error('There is no result to continue.');if(s.receipt.back==='events')nextScene(s);else {s.mode=s.receipt.back;s.receipt=null;}break;
 case 'driver':if(!['map','offers'].includes(s.mode)||!Object.keys(s.energy).includes(a.id))throw Error('Choose a driver while stopped.');s.driver=a.id;break;
 case 'pace':if(s.mode!=='map'||!['steady','scenic','brisk'].includes(a.id))throw Error('Choose a pace while stopped.');s.pace=a.id;break;
 case 'travel':{if(!['map','offers'].includes(s.mode))throw Error('Finish the current stop first.');const q=travelQuote(s,a.id);if(q.error)throw Error(q.error);s.fuel-=q.fuel;s.condition-=q.wear;hours(s,q.hours);s.energy[s.driver]-=q.energy;for(const id of Object.keys(s.energy))if(id!==s.driver)s.energy[id]=clamp(s.energy[id]+q.hours*.8,0,100);s.miles+=q.miles;s.travel={...q,elapsed:0,duration:6};s.mode='travel';log(s,'On the road',`${nodeById(q.from).name} → ${nodeById(q.to).name}. ${q.miles} miles, ${rounded(q.hours)}h, ${rounded(q.fuel)} gallons. ${q.forecast}.`);break;}
 case 'skipTravel':if(s.mode!=='travel')throw Error('The van is not travelling.');arrive(s);break;
 case 'service':{if(['packing','travel','ending','receipt'].includes(s.mode))throw Error('Use supplies while stopped.');const q=serviceQuote(s,a.id);if(q.error)throw Error(q.error);const previous=s.mode;applyEffect(s,q);if(q.fuel)s.fuel=45;if(q.voucher)s.flags.voucher-=q.voucher;if(q.once)s.serviceUses.push(`${s.node}:${a.id}`);log(s,q.label,effectsText(q));receipt(s,q.label,q.desc,effectsText(q),previous);break;}
 case 'plan':if(s.mode!=='offers')throw Error('Choose the next-month plan at arrival.');if(!WORK_PLANS.some(p=>p.id===a.id))throw Error('Unknown work plan.');s.plan=a.id;break;
 case 'consultHome':if(s.mode!=='offers')throw Error('Discuss the home at arrival.');hours(s,.25);s.flags.consulted=true;break;
 case 'accept':{if(s.mode!=='offers')throw Error('Inspect the homes before accepting.');const o=OFFERS.find(o=>o.id===a.id);if(!o)throw Error('Unknown offer.');const q=housingStatus(s,o);if(!q.ok)throw Error(q.reason);s.cash-=q.cost;s.ending={...o,paid:q.cost,subsidy:o.id==='bridge'?120-q.cost:0,remaining:s.cash,plan:s.plan,monthlyIncome:q.income,monthlyMargin:q.monthlyMargin,callbacks:endingCallbacks(s),day:currentDay(s)};s.mode='ending';log(s,o.name,o.id==='bridge'?'A temporary stay and a follow-up appointment. The long-term home is still ahead.':`Moved in for $${q.cost}. Next-month margin: $${q.monthlyMargin}.`);break;}
 case 'bridge':if(['travel','packing','ending'].includes(s.mode))throw Error('Stop before changing the journey.');s.event=null;s.queue=[];s.receipt=null;s.node='R10';if(!s.visited.includes('R10'))s.visited.push('R10');s.mode='offers';log(s,'A changed plan','Arranged a fourteen-night bridge stay and a follow-up housing appointment.');break;
 default:throw Error('Unknown action.');
 }
 s.revision++;s.transactions.push(`${s.revision}:${a.type}:${a.id||''}`);s.transactions=s.transactions.slice(-200);validateState(s);return {ok:true,state:s};
 }catch(e){return {ok:false,state:original,error:e.message};}}
export function advance(s,seconds){if(s.mode!=='travel'||seconds<=0)return s;const n=copy(s);n.travel.elapsed+=Math.min(seconds,30);if(n.travel.elapsed>=n.travel.duration){arrive(n);n.revision++;}return n;}
export function validateState(s){if(s.schema!==1||s.version!==VERSION)throw Error('Unsupported save version.');if(!['packing','event','receipt','map','travel','offers','ending'].includes(s.mode))throw Error('Invalid campaign phase.');if(!nodeById(s.node))throw Error('Invalid location.');for(const k of ['cash','hours','fuel','food','condition','miles','revision','seed'])if(!Number.isFinite(s[k])||s[k]<0)throw Error('Invalid resource: '+k);if(s.cash>1e7||s.fuel>45.01||s.food>8.01||s.condition>100.01)throw Error('Invalid resource bounds.');if(!Array.isArray(s.cargo)||new Set(s.cargo).size!==s.cargo.length||s.cargo.some(id=>!itemById(id))||usedSlots(s)>6)throw Error('Invalid cargo.');for(const id of ['rowan','jules','dani'])if(!Number.isFinite(s.energy[id])||s.energy[id]<0||s.energy[id]>100)throw Error('Invalid energy.');if(!s.flags||!Array.isArray(s.queue)||s.queue.some(id=>!EVENTS[id])||!Array.isArray(s.done)||!Array.isArray(s.journal)||!Array.isArray(s.transactions)||!Array.isArray(s.serviceUses)||!Array.isArray(s.visited))throw Error('Incomplete campaign data.');if(s.mode==='event'&&!EVENTS[s.event])throw Error('Invalid encounter.');if(s.mode==='travel'&&(!s.travel||!EDGES.some(e=>e.id===s.travel.id&&e.to===s.travel.to)||!Number.isFinite(s.travel.elapsed)))throw Error('Invalid travel.');if(s.mode==='receipt'&&(!s.receipt||!['map','offers','event','events'].includes(s.receipt.back)))throw Error('Invalid result.');if(s.mode==='ending'&&(!s.ending||!OFFERS.some(o=>o.id===s.ending.id)))throw Error('Invalid ending.');return true;}
// v0.2 changes art and prose, not the campaign schema or any transaction identity.
// Only the known v0.1 format is upgraded; corrupt and future saves remain rejected.
function readSavedCampaign(raw){const s=JSON.parse(raw);if(s?.schema===1&&s.version==='0.1.0')s.version=VERSION;validateState(s);return s;}
export function saveCampaign(storage,s){validateState(s);const old=storage.getItem(SAVE_KEY);if(old){try{const previous=readSavedCampaign(old);storage.setItem(SAVE_KEY+'-backup',JSON.stringify(previous));}catch{}}storage.setItem(SAVE_KEY,JSON.stringify(s));}
export function loadCampaign(storage){let recovered=false;for(const key of [SAVE_KEY,SAVE_KEY+'-backup']){try{const raw=storage.getItem(key);if(!raw)continue;const s=readSavedCampaign(raw);return {state:s,recovered};}catch{recovered=true;}}return {state:null,recovered};}
export function snapshot(s){return {version:VERSION,mode:s.mode,node:s.node,location:nodeById(s.node).name,day:currentDay(s),hours:rounded(s.hours),cash:rounded(s.cash),reserve:s.reserve,fuel:rounded(s.fuel),food:rounded(s.food),condition:rounded(s.condition),energy:s.energy,cargo:s.cargo,cargoSlots:usedSlots(s),driver:s.driver,pace:s.pace,event:s.event,choices:s.mode==='event'?EVENTS[s.event].choices.map(c=>({id:c.id,label:c.label,...choiceStatus(s,c)})):[],routes:['map','offers'].includes(s.mode)?EDGES.filter(e=>e.from===s.node).map(e=>travelQuote(s,e.id)):[],contract:s.contract,flags:s.flags,ending:s.ending,revision:s.revision,travel:s.travel?{to:s.travel.to,elapsed:rounded(s.travel.elapsed)}:null,coordinates:'Illustrated scene only: x right, y down. Route map is an authored west-to-east graph, not navigation.'};}
