export const BRAND={title:'Signals End',short:'SIGNALS END',tagline:'A home. A deed. Nobody’s permission.',mark:'assets/signals-end/signals-end-stacked-light.svg',provisional:false,identityPending:false};
export const NAMES=[
 {id:'quiet-country',name:'Quiet Country',tag:'THE PROMISE · RECOMMENDED',line:'Leave the signal. Keep your life.',note:'The frontier feeling of Last Free County, with something left unsaid. Quiet means a place that has chosen to disappear.',direction:'Two heavy frontier lines, worn ivory ink and a broken rust horizon. Let the empty space carry the disconnection.'},
 {id:'after-the-signal',name:'After the Signal',tag:'THE LIFE BEYOND',line:'There is a life after being watched.',note:'A more cinematic title. The journey leads toward the life that begins when the digital world ends for this family.',direction:'Stacked slab lettering with a small THE. The last rule stops short, as though the transmission ended.'},
 {id:'the-quiet-republic',name:'The Quiet Republic',tag:'THE HIDDEN REFUGE',line:'A place that chose to disappear.',note:'The strongest name for a rumored society with its own rules. Hopeful at a distance; more complicated at the gate.',direction:'The same worn frontier lettering, arranged like a settlement placard. Restraint, weight and a deliberate gap.'},
 {id:'where-the-wires-end',name:'Where the Wires End',note:'The most lyrical pilgrimage title. You can picture the destination. Longer on a small screen; better suited to a campaign or subtitle.'},
 {id:'leave-no-signal',name:'Leave No Signal',note:'Intentional disconnection as an act of resistance. Sharper and more dangerous; it emphasizes pursuit more than home.'},
 {id:'no-forwarding-address',name:'No Forwarding Address',note:'The dry, human option. A family vanishes without leaving the system a way to bill them. More road novel than survival epic.'}
];
