import {FILM_DURATION,FILM_SCENES,setFilmTime,movePrologue} from './prologue.js?v=0.7.2-canon-2';
// Keep button text nodes stable while a pointer is down (notably in WebKit).
const setLabel=(element,text)=>{if(element.textContent!==text)element.textContent=text;};
export class OpeningPlayer {
 constructor(root,state,{onExit,onSeen,reduced=false}){
  this.root=root;this.state=state;this.onExit=onExit;this.onSeen=onSeen;this.dead=false;this.seen=false;
  this.format=innerHeight>innerWidth?'portrait':'landscape';
  root.innerHTML=`<video id="opening-video" muted playsinline preload="auto" aria-label="Signals End: Run for it. A 96-second opening film." disablepictureinpicture></video><div class="opening-chrome"><div class="opening-top"><span>King Made</span><button data-action="introSkip" aria-label="Skip opening film">Skip ×</button></div><button class="opening-play" data-action="introPlay" hidden>Play film</button><div class="opening-bottom"><span class="opening-a11y" aria-live="polite" id="opening-caption"></span><div class="opening-progress" role="progressbar" aria-label="Opening film progress" aria-valuemin="0" aria-valuemax="96"><i></i></div><div class="opening-controls"><button data-action="introPause" aria-label="Pause film">Pause</button><button data-action="introSound" aria-label="Enable film sound">Sound on</button><span class="opening-time">1:36</span><button data-action="introBack" hidden>←</button><button data-action="introNext" hidden>Next →</button></div></div></div>`;
  this.video=root.querySelector('video');const v=this.video;v.muted=true;v.defaultMuted=true;v.playsInline=true;
  v.addEventListener('playing',()=>{if(this.dead)return;if(state.source!=='video'&&state.time>.25&&Math.abs(v.currentTime-state.time)>.4)v.currentTime=state.time;state.source='video';state.paused=false;state.blocked=false;this.mark();this.updateUI();});
  v.addEventListener('ended',()=>{if(!this.dead)this.onExit('watched');});
  v.addEventListener('error',()=>this.fallback());
  v.addEventListener('pause',()=>{if(!this.dead&&state.source==='video'&&!v.ended){state.paused=true;this.updateUI();}});
  if(reduced){state.source='stills';state.paused=true;setFilmTime(state,.8);v.preload='none';}else{v.src=`assets/opening-08/run-for-it-${this.format}.mp4?art=van-1`;this.play();}
  this.updateUI();
 }
 mark(){if(!this.seen){this.seen=true;this.onSeen();}}
 fallback(){if(this.dead||this.state.source==='stills')return;this.state.source='illustrated';this.state.blocked=false;this.state.paused=false;this.video.pause();this.updateUI();}
 play(){if(this.dead)return;const p=this.state;if(p.source==='stills')return;p.paused=false;p.blocked=false;if(p.source==='illustrated'){this.mark();this.updateUI();return;}this.video.play().catch(error=>{if(this.dead)return;if(error.name==='NotAllowedError'){p.blocked=true;p.paused=true;this.updateUI();}else if(error.name!=='AbortError')this.fallback();});this.updateUI();}
 pause(){this.state.paused=true;this.video.pause();this.updateUI();}
 action(type){const p=this.state;if(type==='introSkip'){this.onExit('skipped');return;}if(type==='introPlay'){this.play();return;}if(type==='introPause'){p.paused?this.play():this.pause();return;}if(type==='introSound'&&p.source!=='stills'&&p.source!=='illustrated'){p.muted=!p.muted;this.video.muted=p.muted;if(!p.muted&&p.paused)this.play();this.updateUI();return;}if(p.source==='stills'&&(type==='introNext'||type==='introBack')){if(type==='introNext'&&p.index===FILM_SCENES.length-1){this.onExit('watched');return;}movePrologue(p,type==='introNext'?1:-1);this.mark();this.updateUI();}}
 tick(dt){if(this.dead)return;const p=this.state;if(!p.paused){if(p.source==='video')setFilmTime(p,this.video.currentTime);else if(p.source==='loading'||p.source==='illustrated'){setFilmTime(p,p.time+dt);if(p.time>.3)this.mark();}if(p.time>=FILM_DURATION){this.onExit('watched');return;}}this.updateUI();}
 advance(seconds){if(this.dead)return;const p=this.state;if(p.paused)return;const next=p.time+seconds;setFilmTime(p,next);if(p.source==='video'&&this.video.readyState>=1)this.video.currentTime=Math.min(next,FILM_DURATION-.05);if(next>=FILM_DURATION)this.onExit('watched');else this.updateUI();}
 updateUI(){if(this.dead)return;const p=this.state,v=this.video;v.classList.toggle('is-playing',p.source==='video'&&v.readyState>=2);const play=this.root.querySelector('.opening-play');play.hidden=!p.blocked;const pause=this.root.querySelector('[data-action="introPause"]');setLabel(pause,p.paused?'Play':'Pause');pause.setAttribute('aria-label',p.paused?'Play film':'Pause film');pause.hidden=p.source==='stills';const sound=this.root.querySelector('[data-action="introSound"]');setLabel(sound,p.muted?'Sound on':'Mute');sound.setAttribute('aria-label',p.muted?'Enable film sound':'Mute film sound');sound.hidden=['stills','illustrated'].includes(p.source);for(const a of ['introBack','introNext'])this.root.querySelector(`[data-action="${a}"]`).hidden=p.source!=='stills';this.root.querySelector('[data-action="introBack"]').disabled=p.index===0;setLabel(this.root.querySelector('[data-action="introNext"]'),p.index===FILM_SCENES.length-1?'Finish':'Next →');const remaining=Math.max(0,Math.ceil(FILM_DURATION-p.time));setLabel(this.root.querySelector('.opening-time'),p.source==='stills'?`${p.index+1} / ${FILM_SCENES.length}`:`${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')}`);const progress=this.root.querySelector('.opening-progress');progress.setAttribute('aria-valuenow',String(Math.round(p.time)));progress.firstElementChild.style.width=(p.time/FILM_DURATION*100)+'%';const line=FILM_SCENES[p.index].line,caption=this.root.querySelector('#opening-caption');if(caption.textContent!==line)caption.textContent=line;}
 destroy(){this.dead=true;this.video.pause();this.video.removeAttribute('src');this.video.load();this.root.innerHTML='';}
}
