import {startHunting,huntingAction,updateHunting,migrateHunting} from './hunting.js?v=0.8.4-apps-1';
import {VERSION,SAVE_KEY,PACKING,PARTS,ROADS,CAMPAIGN,objective,admission,node,random,siteItems} from './world.js?v=0.8.4-apps-1';
import {startFishing,fishingAction,updateFishing} from './fishing.js?v=0.8.4-apps-1';
import {startSalvage,salvageAction,updateSalvage,saveSite} from './salvage.js?v=0.8.4-apps-1';
import {showStory,roadShots,updateReel,ARRIVALS} from './journey.js?v=0.8.4-apps-1';
import {clamp,log,slots,consumeFresh,spend,finish,hurt,shopStock,OFFERS} from './state.js?v=0.8.4-apps-1';
import {makeIncident,resolveIncident} from './conflict.js?v=0.8.4-apps-1';
import {advanceRoad} from './drive.js?v=0.8.4-apps-1';
import {initialNarrativeFlags,arriveNarrative,migrateNarrative,knowledge,ORIGIN,RADIO_MESSAGE} from './narrative.js?v=0.8.4-apps-1';
export {clamp,log,slots,consumeFresh,spend,finish};
export function fresh(seed=42){return {version:VERSION,seed,mode:'packing',node:'yard',hour:0,deadline:CAMPAIGN.departureWindow,cash:240,fuel:34,meals:4,energy:88,health:100,condition:82,fan:false,packed:['cooler','spare','chair'],parts:{fan:[],relay:[],tire:[]},cargo:null,sponsor:false,visited:['yard'],sites:{},jobs:[],activity:null,road:null,incident:null,ending:null,home:{placed:[],spot:'window'},journal:[{hour:0,title:'Why we left',body:ORIGIN},{hour:0,title:'Ben’s handwritten broadcast',body:RADIO_MESSAGE}],flags:initialNarrativeFlags(),settings:{castMode:'tap',autoHook:false,toggleReel:false,reducedMotion:false,sound:false,mirror:false},effects:{handUntil:0},stocks:{},freshFood:[],fishSites:{},hunting:{outfitted:false,ammo:0,taken:[],shots:0,outings:0,shared:false},siteMemory:{},threat:{permitUsed:false,firstEncounter:false,identified:false,heat:0,encounters:0,relief:0},reel:{seen:[],gallery:['broadcast']},story:null,activeTime:0,stats:{hunts:0,fish:0,salvaged:0,repairs:0,miles:0,encounters:0},message:'',revision:0};}
export function load(storage){try{const s=JSON.parse(storage.getItem(SAVE_KEY));if(s?.version===VERSION&&Number.isFinite(s.hour)&&s.parts&&s.effects&&s.stocks&&s.threat&&s.reel&&Number.isFinite(s.fuel)&&Array.isArray(s.journal))return migrateHunting(migrateNarrative(s));}catch{}return null;}
export function save(storage,s){storage.setItem(SAVE_KEY,JSON.stringify(s));}
export function startActivity(s,type,target='van'){
 if(s.mode!=='stop')throw Error('Finish the current activity first.');
 if(s.energy<8)throw Error('Rest with the family before working.');
 if(type==='hunting'){startHunting(s);return;}else if(type==='salvage'){if(!node(s.node).salvage)throw Error('No accessible site here.');startSalvage(s);return;}else if(type==='fishing'){if(!node(s.node).fish)throw Error('There is no fishing access here.');startFishing(s);return; }else if(type==='repair'){
  if(target==='van'&&s.fan&&s.condition>=95)throw Error('The van is running well.');
  if(target==='pump'&&s.node!=='pump')throw Error('Reach the pump house first.');
  if(target==='pump'&&s.sponsor)throw Error('The pump is already restored.');
  s.activity=s.jobs.find(job=>job.target===target)||{type,target,elapsed:0,duration:0,phase:'replace',tested:[target==='pump'?'relay':!s.fan?'fan':'tire'],fault:target==='pump'?'relay':!s.fan?'fan':'tire',selected:null,installed:false,connections:[],tune:.3,running:false,stable:0,notice:target==='pump'?'Burnt pump relay. Fit a replacement, then choose how to finish the repair.':!s.fan?'Seized cooling fan. Fit a replacement to stop wasting fuel on every drive.':'The tires are worn. Fit a spare to restore road condition.'};
 }else throw Error('Unknown activity.');
 s.mode=type;
}
export function endActivity(s){
 const a=s.activity;if(!a)return;if(a.type==='hunting'){huntingAction(s,{type:'huntLeave'});return;}
 let hours=0;
 if(a.type==='salvage'){saveSite(s);s.energy-=7;log(s,'Back at the van',a.collected.length?`${a.collected.join(', ')} recovered. ${s.threat.identified?'They recorded the plate. Be careful at checkpoints.':'Everyone is back in the van.'}`:'You left the yard. Knowing when to stop counts too.');}
 if(a.type==='fishing'){s.energy-=3;log(s,'Lines in',a.catch?`${a.catch} portions kept. Ben is already planning dinner.`:'Nothing landed this time. The river keeps its secrets.');}
 if(a.type==='repair'){
  s.energy-=8;
  if(a.phase==='done'){
   s.stats.repairs++;s.jobs=s.jobs.filter(job=>job.target!==a.target);
   if(a.target==='pump'){s.sponsor=true;s.flags.pumpDone=true;s.meals+=2;s.fuel=Math.min(50,s.fuel+4);s.cash+=25;log(s,'Water running',"Glenn signs the household papers. Jack fixed the pump himself; nobody billed him for permission. Two meals, four fuel and $25. The water keeps running after work ends.");}
   else {if(a.fault==='fan')s.fan=true;s.condition=clamp(s.condition+14+(a.quality||80)*.2,0,100);log(s,'That sounds better',a.fault==='fan'?'A working fan. No service login. Ben asks Jack to show him again; this time Jack has time.':'The van is ready for the next rough stretch.');}
  }else {s.jobs=s.jobs.filter(job=>job.target!==a.target);s.jobs.push({...structuredClone(a),elapsed:0});log(s,'Hood closed','Your repair work is still in place. Find a part, rest, or return to finish it.');}
 }
 s.energy=clamp(s.energy,0,100);s.activity=null;s.mode='stop';spend(s,hours);if(a.type==='fishing'&&a.catch>0&&s.mode==='stop'&&!s.flags.fishDinner){showStory(s,'dinner');s.flags.fishDinner=true;}
}
export function act(s,a){
 s.message='';
 if(huntingAction(s,a)||fishingAction(s,a)||salvageAction(s,a)){s.revision++;return s;}
 switch(a.type){
 case 'pack':{if(s.mode!=='packing')throw Error('Packing has finished.');const item=PACKING.find(i=>i.id===a.id);if(!item)throw Error('Unknown item.');if(s.packed.includes(a.id))s.packed=s.packed.filter(i=>i!==a.id);else if(s.packed.reduce((v,id)=>v+PACKING.find(i=>i.id===id).slots,0)+item.slots<=6)s.packed.push(a.id);else throw Error('Six spaces. Leave something to make room.');break;}
 case 'depart':if(s.mode!=='packing')throw Error('Already on the road.');if(s.packed.includes('spare'))s.parts.tire.push(95);if(s.packed.includes('battery'))s.parts.relay.push(90);if(s.packed.includes('provisions'))s.meals+=4;s.mode='travel';s.road={...ROADS.find(r=>r.id==='opening'),elapsed:0,duration:18,meters:0,mph:0,wheelAngle:0,eventDone:true,shots:[],shot:null};s.road.shots=roadShots(s,s.road);log(s,'San Francisco, behind us','Jack’s employer fired him for refusing an unsafe sign-off. Cash froze the joint wallet. The appeal would come after the housing deadline. Ten minutes to load the basics; now we’re crossing the Bay. Sarah has her questions, Ben has the broadcast on paper. The contract charge follows the household. A plate scan can turn that record into a Collector sighting.');break;
 case 'activity':startActivity(s,a.id,a.target);break;
 case 'leaveActivity':if(s.mode==='salvage'&&s.activity.phase==='intercept')throw Error('Deal with the officer first.');endActivity(s);break;
 case 'test':{const g=s.activity;if(s.mode!=='repair'||g.phase!=='diagnose')throw Error('Inspect before replacing.');if(!g.tested.includes(a.id)){g.tested.push(a.id);g.elapsed+=8;}g.notice=a.id===g.fault?({fan:'Fan motor seized. Replace the cooling fan.',relay:'Burnt relay. Power stops here.',tire:'Sidewall split. Fit a spare tire.'}[g.fault]):({fan:'Fan spins freely. Keep looking.',relay:'Power is reaching this connection.',tire:'Tire holds pressure. No leak here.'}[a.id]);if(a.id===g.fault)g.phase='replace';break;}
 case 'fit':{const g=s.activity;if(s.mode!=='repair'||g.phase!=='replace')throw Error('Find the fault first.');if(a.id!==g.fault){g.notice='That part does not fit this fault.';break;}if(!s.parts[a.id]?.length)throw Error(`Find or buy a ${PARTS[a.id].name.toLowerCase()} first.`);g.quality=s.parts[a.id].shift();g.installed=true;g.phase='method';g.notice='A clean fit. Work carefully, or tune it by feel to save time.';break;}
 case 'repairMethod':{const g=s.activity;if(s.mode!=='repair'||g.phase!=='method')throw Error('Fit the part first.');g.phase=a.id==='steady'?'steady':'tune';g.stable=0;g.elapsed=0;g.tuneCenter=.58+((s.seed+s.stats.repairs*3)%5)*.035;g.notice=a.id==='steady'?'Ben holds the light. Jack checks the fit.':'Move the regulator into the brass band and hold it there.';spend(s,a.id==='steady'?(hurt(s)?2:1.5):.5);break;}
 case 'tune':if(s.mode==='repair'&&s.activity.phase==='tune')s.activity.tune=clamp(a.value,0,1);break;
 case 'rest':if(s.mode!=='stop')throw Error('Stop to rest.');spend(s,4);if(s.mode==='ending')break;s.energy=Math.min(100,s.energy+40);s.health=Math.min(100,s.health+8);log(s,'Four quiet hours','Sarah wakes expecting an attention warning. Only Rusty is watching. Four hours of sleep; nobody docked their pay.');break;
 case 'meal':if(s.mode!=='stop')throw Error('Stop to eat.');if(s.meals<1)throw Error('You need a household meal. Hunt, fish, trade, or salvage food.');s.meals--;consumeFresh(s,1);spend(s,.5);if(s.mode==='ending')break;s.energy=Math.min(100,s.energy+15);s.health=Math.min(100,s.health+12);log(s,'Something warm','Dinner without a checkout camera. Annie finishes her story before anyone interrupts. For half an hour, the road can wait.');showStory(s,'dinner');break;
 case 'buy':{if(s.mode!=='stop'||!node(s.node).shop)throw Error('No trading here.');const o=OFFERS[a.id],stock=shopStock(s,s.node);if(!o||!stock[a.id])throw Error('That supply is sold out at this stop.');if(s.cash<o.price)throw Error('Not enough cash. Recover or trade a spare.');if(PARTS[a.id]&&slots(s)>=7)throw Error('Parts locker full.');if(a.id==='fuel'&&s.fuel>36)throw Error('Use some fuel first; this is a sealed 14-unit can.');s.cash-=o.price;stock[a.id]--;if(a.id==='fuel')s.fuel+=14;else if(a.id==='food')s.meals+=3;else s.parts[a.id].push(90);spend(s,.25);s.message=o.label+' aboard. The trader has limited stock.';break;}
 case 'sell':if(s.mode!=='stop'||!node(s.node).shop)throw Error('Find a trader first.');if(!s.parts[a.id]?.length)throw Error('No spare to trade.');s.parts[a.id].shift();s.cash+=25;spend(s,.2);s.message='Part traded for $25. The trader tests the mechanism, not your account.';break;
 case 'delivery':if(s.mode!=='stop'||!['freight','ridge'].includes(s.node))throw Error('Find the Pruitt convoy.');if(s.cargo&&s.cargo.condition>=45)throw Error('The filters are already aboard.');if(s.cargo&&s.node!=='ridge')throw Error('Ask the Pruitts for a replacement crate at the ridge.');if(s.cargo&&s.flags.replacementFilters)throw Error('The spare crate is already used. Seek Glenn’s sponsorship or the outer camp.');if(slots(s)-(s.cargo?3:0)>4)throw Error('The crate needs three locker spaces. Fit or trade parts first.');const replacing=!!s.cargo;if(replacing)s.flags.replacementFilters=true;s.cargo={condition:replacing?80:100};s.flags.tarp=true;spend(s,replacing?3:1.5);log(s,'A place on the manifest','Wes Pruitt matched Frank’s letter to the household reservation. The crate is covered and tied down. Get the filters to Signals End intact.');break;
 case 'hideout':if(s.mode!=='stop'||s.node!=='ridge')throw Error('The safe contact is at the ridge.');if(s.flags.hideout)throw Error('The quiet approach is already marked.');if(!s.flags.safeContact&&s.cash<15)throw Error('The guide needs $15 for fuel.');if(!s.flags.safeContact)s.cash-=15;spend(s,s.flags.safeContact?2:3);s.threat.heat=0;s.threat.relief=60;s.flags.hideout=true;log(s,'The truck takes the wrong road','A local guide moves the van through a covered service tunnel. Your plate remains recorded; the pursuit loses your route.');break;
 case 'aid':if(s.mode!=='stop'||s.flags.aid)throw Error('The road network’s emergency supplies are already used.');if(s.cash>20&&s.fuel>8&&s.meals>1)throw Error('Keep the emergency supplies for a household in trouble.');s.flags.aid=true;s.fuel+=8;s.meals+=2;spend(s,4);log(s,'A costly kindness','The nearest road contact found a little fuel and food. Four hours lost arranging it. Make this chance count.');break;
 case 'travel':{if(s.mode!=='stop')throw Error('Finish your stop first.');const r=ROADS.find(r=>r.id===a.id&&r.from===s.node);if(!r)throw Error('That road does not leave here.');if(s.fuel<r.fuel+(!s.fan?2:0))throw Error('Not enough fuel for this leg. Trade, recover supplies, or seek help.');if(s.condition<=5)throw Error('The van cannot move. Repair the running gear.');s.road={...r,fuel:r.fuel+(!s.fan?2:0),wear:r.wear+(!s.fan?6:0),elapsed:0,meters:0,wheelAngle:0,mph:0,duration:24,eventDone:false,pace:a.pace||'steady',startFuel:s.fuel};s.road.shots=roadShots(s,r);s.road.shot=null;s.mode='travel';s.message='';break;}
 case 'incident':{if(s.mode!=='incident')throw Error('No road encounter.');resolveIncident(s,a.id);if(s.mode==='ending')break;if(s.condition<=0||s.health<=0){finish(s,'stranded','The road asked too much.','Road volunteers brought the family to a county shelter. The run is over; everyone is alive.');break;}s.mode='travel';s.incident=null;s.road.shot=null;break;}
 case 'storyContinue':if(s.mode!=='story')throw Error('No story to continue.');s.mode=s.story.returnMode;s.story=null;break;
 case 'skipShot':if(s.mode==='travel')s.road.shot=null;break;
 case 'setting':if(!['castMode','autoHook','toggleReel','reducedMotion','sound','mirror'].includes(a.id))throw Error('Unknown setting.');s.settings[a.id]=a.id==='castMode'?(a.value==='tap'?'tap':'pull'):!!a.value;break;
 case 'gate':{if(s.mode!=='stop'||s.node!=='line')throw Error('Reach the Line first.');if(s.hour>s.deadline){finish(s,'outside','The lights went out before you crossed.','The scheduled convoy has gone and the storm closed the service bridge. Your family is safe in the outer camp, but the home you came for is still beyond the Line.');break;}if(!s.sponsor&&!(s.cargo&&s.cargo.condition>=45)){s.message='Evelyn needs a sponsor or a usable filter delivery. You can seek the ridge convoy, or accept a place in the outer camp.';break;}s.flags.charterAccepted=true;s.flags.devicesStored=true;log(s,'A choice at the Line','Ben puts the dead handheld in a numbered storage box. The family accepts the same analog charter as the council. Evelyn releases their household reservation.');s.mode='crossing';s.activity={type:'crossing',elapsed:0,duration:50,x:.5,target:.5,speed:.65,distance:0,damage:0,hits:[],obstacles:Array.from({length:8},(_,i)=>({id:i,z:.16+i*.105,x:[.27,.7,.5,.25,.73,.48][(i+s.seed)%6],size:.1})),notice:'Drag to steer. Hold Slow for more room. Reach the warm lights.'};break;}
 case 'returnRidge':if(s.node!=='line'||s.mode!=='stop')throw Error('You are not at the Line.');if(s.fuel<5)throw Error('You need 5 fuel to return. Emergency aid may help.');spend(s,5);s.fuel-=5;s.node='ridge';s.message='Back to the ridge. The Pruitts may still have a filter crate.';break;
 case 'outer':if(s.mode!=='stop'||s.node!=='line')throw Error('Reach the Line first.');finish(s,'outside','Together, outside the Line.','You chose the outer settlement. The family survived the pilgrimage. An analog life is still a promise across the water.');break;
 case 'rescue':if(s.mode!=='stop')throw Error('Stop before calling relief transport.');finish(s,'stranded','You kept the family together.','Independent road volunteers bring everyone to a county shelter. The run is over. Returning to a company contract is one hard choice still ahead, not a decision made for you.');break;
 case 'steer':if(s.mode==='crossing')s.activity.target=clamp(a.value,.12,.88);break;
 case 'slow':if(s.mode==='crossing')s.activity.speed=a.value?.36:.7;break;
 case 'homeItem':if(s.mode!=='home')throw Error('You have not arrived.');if(!['key','picture','lamp','table'].includes(a.id))throw Error('Unknown keepsake.');if(!s.home.placed.includes(a.id))s.home.placed.push(a.id);if(a.id==='key')s.message='The key turns. No camera wakes. Nobody asks who signed in.';if(a.id==='picture')s.message='“Can we put holes in the wall?” “It’s our wall.”';if(a.id==='lamp')s.message='Click. The light obeys. Ben turns it off, then on again, just because he can.';if(a.id==='table')s.message='Four places. Rusty underneath. Annie talks; both parents listen. No camera asks them to check in.';break;
 case 'homeSpot':if(s.mode!=='home'||!['window','workshop'].includes(a.id))throw Error('Choose a place at home.');s.home.spot=a.id;break;
 case 'finishHome':if(s.mode!=='home'||s.home.placed.length<4)throw Error('Make yourselves at home first.');finish(s,'home','The evening belongs to you.','Jack puts down the wrench. Sarah stays at the table. The machines can wait until morning. No shift to extend. No camera checking. This part of your life is yours.');break;
 default:throw Error('Unknown action.');
 }
 s.revision++;
 return s;
}
export function update(s,dt){
 if(!Number.isFinite(dt)||dt<0)return;
 s.activeTime+=dt;s.threat.relief=Math.max(0,s.threat.relief-dt);
 if(s.mode==='story'){s.story.elapsed+=dt;return;}
 if(s.mode==='hunting'){updateHunting(s,dt);return;}
 if(s.mode==='fishing'){spend(s,dt*.018);if(s.mode==='fishing')updateFishing(s,dt);return;}
 if(s.mode==='salvage'){if(s.activity.phase!=='intercept')spend(s,dt*.025);if(s.mode!=='salvage')return;updateSalvage(s,dt);if(s.mode==='salvage'&&s.activity.phase==='exit')endActivity(s);return;}
 if(s.mode==='travel'){
  const r=s.road,step=Math.min(dt,Math.max(0,r.duration-r.elapsed));advanceRoad(r,step);updateReel(s,step);
  const fraction=step/r.duration;s.fuel=Math.max(0,s.fuel-r.fuel*fraction);spend(s,r.hours*fraction);if(s.mode==='ending')return;
  if(s.fuel<=.001&&r.fuel>0&&r.elapsed<r.duration-.001){s.fuel=0;s.node=r.from;s.mode='stop';s.road=null;spend(s,3);if(s.mode==='stop')log(s,'Running on empty','A local recovery driver towed you back. Three hours gone. Find fuel before trying again.');return;}
  if(!r.eventDone&&r.elapsed>=r.duration*.48){r.eventDone=true;s.incident=makeIncident(s,r);s.mode='incident';return;}
  if(r.elapsed>=r.duration){s.node=r.to;s.visited.push(r.to);s.stats.miles+=r.miles??Math.round(r.hours*35);s.condition=Math.max(0,s.condition-r.wear);s.energy=clamp(s.energy-r.hours*2.4,0,100);if(s.energy<15)s.health=Math.max(1,s.health-7);if(s.cargo&&r.kind==='storm')s.cargo.condition=clamp(s.cargo.condition-(s.flags.tarp?3:12));s.mode='stop';s.road=null;arriveNarrative(s,s.node);if(s.condition<=0){log(s,'The van gives out at the stop','You coast into the yard. Repair the running gear before driving again.');return;}if(s.mode==='stop'){log(s,node(s.node).name,node(s.node).desc);const arrival=ARRIVALS[s.node];if(arrival&&!s.reel.seen.includes(arrival))showStory(s,arrival);}}
 }
 const g=s.activity;if(!g)return;
 g.elapsed+=dt;
 if(s.mode==='repair'&&g.phase==='tune'){
  spend(s,dt*.01);if(s.mode==='ending')return;const center=g.tuneCenter||.67,band=hurt(s)?.055:.09;if(g.tune>=center-band&&g.tune<=center+band)g.stable+=dt;else g.stable=Math.max(0,g.stable-dt*.7);
  if(g.stable>=4){g.phase='done';g.notice=g.target==='pump'?'Water flows. Glenn is signing the household papers.':g.fault==='tire'?'Even tension. The new tire is seated and secure.':'Listen to that. A steady engine. A road worth taking.';}
 }
 if(s.mode==='repair'&&g.phase==='steady'&&g.elapsed>=5){g.phase='done';g.notice='Everything secured. The machine runs smoothly.';}
 if(s.mode==='crossing'){
  g.x+=(g.target-g.x)*Math.min(1,dt*5);g.distance+=dt*g.speed/35;
  for(const ob of g.obstacles){const z=ob.z-g.distance;if(z<.045&&z>-.02&&!g.hits.includes(ob.id)&&Math.abs(g.x-ob.x)<.13){g.hits.push(ob.id);g.damage+=g.speed>.5?16:7;s.condition=Math.max(0,s.condition-(g.speed>.5?12:5));if(s.cargo)s.cargo.condition-=g.speed>.5?9:3;g.notice='A hard scrape. Ease off and choose your line.';}}
  if(s.condition<=0){finish(s,'stranded','So close you could see the lights.','The van could go no farther. The crossing crew brought your family to safety, but you missed this intake.');return;}
  if(g.distance>=1){if(s.cargo&&s.cargo.condition<45&&!s.sponsor){finish(s,'outside','The delivery did not make it.','The crossing crew brings the family to the sheltered landing. The damaged filters cannot fulfill the agreement; they escort you to the outer camp. The reservation is not a deed yet.');return;}s.mode='home';s.activity=null;spend(s,1);if(s.mode==='ending')return;s.message='“Mercer household? Welcome home.”';log(s,'Across the Line','The family left its digital devices at the Line. Evelyn recorded the household on paper. Electric lights. A mechanical pump. No screens. Ben recognizes the old water wheels from the broadcast. This time he is here.');}
 }
}
export function summary(s){return {version:s.version,journey:{origin:CAMPAIGN.origin,destination:CAMPAIGN.destination,region:CAMPAIGN.region,chapter:node(s.node)?.chapter,knowledge:knowledge(s),convoyKnown:!!s.flags.convoyKnown,objective:objective(s),admission:admission(s),day:Math.floor(s.hour/24)+1,visited:s.visited,charterAccepted:!!s.flags.charterAccepted,devicesStored:!!s.flags.devicesStored},mode:s.mode,node:s.node,hours:s.hour,remaining:Math.max(0,s.deadline-s.hour),fuel:Math.round(s.fuel*10)/10,meals:Math.round(s.meals*10)/10,energy:Math.round(s.energy),health:Math.round(s.health),condition:Math.round(s.condition),fan:s.fan,cash:s.cash,parts:s.parts,slots:slots(s),packed:s.packed,sponsor:s.sponsor,cargo:s.cargo,home:s.home,ending:s.ending,activity:s.activity,road:s.road,incident:s.incident,site:s.mode==='salvage'?s.sites[s.node]:undefined,message:s.message,threat:s.threat,stats:s.stats,settings:s.settings,reel:s.reel,story:s.story,hunting:s.hunting,fishSites:s.fishSites,freshFood:s.freshFood,activeTime:s.activeTime,effects:s.effects,stocks:s.stocks};}
