// Pure mix and transition rules. No music is generated by this system.
export function soundSnapshot(s){const g=s.activity||{};return {mode:s.mode,node:s.node,phase:g.phase,patrol:g.patrol?.state,shots:s.hunting?.shots||0,fish:s.stats.fish,collected:s.stats.salvaged,repairs:s.stats.repairs,hits:g.hits?.length||0,departure:s.departure?.index,story:s.story?.id,incident:s.incident?.result?.choice};}
export function transitionSounds(p,n){
 if(!p)return [];
 const cues=[];
 if(n.shots>p.shots)cues.push('shot');
 if(n.collected>p.collected)cues.push('stow');
 if(n.hits>p.hits&&n.mode==='crossing'&&p.mode==='crossing')cues.push('scrape');
 if(n.mode==='fishing'&&(p.mode!==n.mode||p.phase!==n.phase)){
  const cue={cast:'cast',wait:'splash',bite:'bite',fight:'hook',landing:'splash',landed:'net',empty:'slip'}[n.phase];if(cue)cues.push(cue);
 }
 if(n.patrol!==p.patrol&&['warning','watch','search'].includes(n.patrol))cues.push(n.patrol==='warning'?'safety':'step');
 if(n.mode==='incident'&&p.mode!==n.mode)cues.push('brake');
 if(n.mode==='travel'&&p.mode==='packing')cues.push('start');
 if(n.mode==='repair'&&n.phase==='done'&&p.phase!=='done')cues.push('start');
 if(n.mode==='story'&&(p.mode!=='story'||p.story!==n.story))cues.push(['nevada-room','frank-key'].includes(n.story)?'key':n.story==='hunt-dinner'||n.story==='dinner'?'bowl':n.story==='ben-wrench'?'switch':n.story==='pump-work'?'start':'paper');
 if(n.mode==='departure'&&p.departure!==n.departure)cues.push(n.departure>=7?'stow':'switch');
 return cues;
}
export function soundMix(s,ui={}){
 const audible=!!s.settings.sound&&!ui.paused&&!ui.title&&!ui.prologue&&!ui.hidden;
 const g=s.activity||{},travel=s.mode==='travel'&&!s.road?.shot,water=s.mode==='fishing',storm=s.road?.kind==='storm'||s.mode==='crossing';
 const working=s.mode==='repair'&&['steady','tune','done'].includes(g.phase);
 return {audible,engine:travel?.19:s.mode==='crossing'?.11:working?.045:0,tires:travel?.20:0,wind:storm?.095:travel?.04:['stop','salvage','hunting'].includes(s.mode)?.026:0,water:water?.30:s.mode==='home'?.016:0,rain:storm?.17:0,reel:water&&g.phase==='fight'&&(g.reel||g.behavior==='run'),working:s.mode==='salvage'&&!!g.working||s.mode==='repair'&&g.phase==='steady',danger:s.mode==='salvage'&&['watch','search'].includes(g.patrol?.state),rpm:travel?42+(s.road.mph||0)*.65:working?32+(g.tune||.3)*35:36,sfx:Math.max(0,Math.min(1,s.settings.sfxVolume??.8)),ambience:Math.max(0,Math.min(1,s.settings.ambienceVolume??.7))};
}
